import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// 번역 데이터
const translations: Record<Language, Record<string, string>> = {
  ko: {
    // 로그인 페이지
    'auth.title': 'LoBo',
    'auth.subtitle': '대학교 AI 챗봇 시스템',
    'auth.login': '로그인',
    'auth.username': '학번/교번',
    'auth.usernamePlaceholder': '예: 2024001234 또는 F2024001',
    'auth.password': '비밀번호',
    'auth.passwordPlaceholder': '비밀번호를 입력하세요.',
    'auth.forgotPassword': '비밀번호를 잊으셨나요?',
    'auth.forgotPasswordMessage': '관리자에게 문의하여 비밀번호를 재설정해주세요.',
    'auth.loginButton': '로그인',
    'auth.loggingIn': '로그인 중...',
    'auth.demoAccounts': '데모 계정으로 빠른 로그인',
    'auth.studentAccount': '👨‍🎓 학생 계정',
    'auth.facultyAccount': '👨‍🏫 교직원 계정',
    'auth.masterAccount': '🔑 마스터 계정',
    'auth.adminSystem': '관리자 시스템',
    'auth.demoStudentDesc': '장지훈 (user1082) - 인문대학 / 국어국문학과 / 현대문학전공, 학생',
    'auth.demoFacultyDesc': '정수빈 (user1081) - 인문대학 / 국어국문학과 / 현대문학전공, 교수, 에이전트 관리자',
    'auth.demoMasterDesc': 'Master Admin (master_admin) - LoBo AI 챗봇 통합 관리자 센터 접근',
    'auth.autoCreate': '계정이 없는 경우 자동으로 생성됩니다',
    'auth.loginSuccess': '로그인 성공',
    'auth.welcome': '환영합니다!',
    'auth.loginFailed': '로그인 실패',
    'auth.loginError': '학번/교번 또는 비밀번호를 확인해주세요.',
    'auth.settings': '설정',
    'auth.themeSettings': '테마 설정',
    'auth.languageSettings': '언어 설정',
    'auth.usernameRequired': '학번/교번을 입력해주세요',
    'auth.passwordRequired': '비밀번호를 입력해주세요',
    'auth.passwordMinLength': '비밀번호는 6자 이상이어야 합니다',
    'auth.firstNameRequired': '이름을 입력해주세요',
    'auth.lastNameRequired': '성을 입력해주세요',
    'auth.emailInvalid': '올바른 이메일 주소를 입력해주세요',
    
    // 공통 UI 요소
    'common.home': '홈',
    'common.chat': '채팅',
    'common.management': '관리',
    'common.logout': '로그아웃',
    'common.loading': '로딩 중...',
    'common.search': '검색',
    'common.files': '파일',
    'common.settings': '설정',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.delete': '삭제',
    'common.edit': '수정',
    'common.upload': '업로드',
    'common.download': '다운로드',
    'common.error': '오류',
    'common.success': '성공',
    
    // 홈페이지
    'home.searchPlaceholder': '에이전트 검색...',
    'home.categories.all': '전체',
    'home.categories.school': '학교',
    'home.categories.professor': '교수',
    'home.categories.student': '학생',
    'home.categories.group': '그룹',
    'home.categories.function': '기능형',
    'home.accountSettings': '계정 설정',
    'account.regularUser': '일반 사용자',
    'account.agentManager': '에이전트 관리자',
    'account.masterAdmin': '마스터 관리자',
    'account.operationManager': '운영 관리자',
    'account.categoryManager': '카테고리 관리자',
    'account.qaManager': 'QA 관리자',
    'account.documentManager': '문서 관리자',
    'account.externalUser': '외부 사용자',
    'account.active': '활성',
    'account.inactive': '비활성',
    'account.locked': '잠금',
    'account.pending': '대기',
    'account.unknown': '알 수 없음',
    'file.validate': '검증',
    'file.overwrite': '덮어쓰기',
    'file.add': '추가',
    'file.uploadComplete': '파일 {action} 완료',
    'file.uploadSuccess': '파일이 성공적으로 {action}되었습니다.',
    'file.deleteComplete': '삭제 완료',
    'file.deleteSuccess': '파일이 성공적으로 삭제되었습니다.',
    'file.deleteFailed': '삭제 실패',
    'file.deleteError': '파일 삭제에 실패했습니다.',
    'file.unsupportedFormat': '지원하지 않는 파일 형식',
    'file.formatRequirement': 'Excel(.xlsx, .xls) 또는 CSV(.csv) 파일만 업로드 가능합니다.',
    'file.sizeExceeded': '파일 크기 초과',
    'file.sizeLimit': '50MB 이하의 파일만 업로드 가능합니다.',
    'file.downloadFailed': '다운로드 실패',
    'file.downloadError': '샘플 파일 다운로드에 실패했습니다.',
    'file.sampleFileName': '사용자업로드_샘플파일.xlsx',
    'home.selectAgent': '에이전트를 선택하세요',
    'home.selectAgentDesc': '왼쪽에서 대화하고 싶은 에이전트를 선택하면 여기에 채팅창이 나타납니다.',
    'home.manageAgent': '관리할 에이전트를 선택하세요',
    'home.manageAgentDesc': '왼쪽에서 관리하고 싶은 에이전트를 선택하면 여기에 관리 인터페이스가 나타납니다.',
    
    // 에이전트 관리
    'agent.management': '에이전트 관리',
    'agent.managementDesc': '관리 중인 에이전트를 선택하여 설정하세요',
    'agent.persona': '페르소나 변경',
    'agent.iconChange': '아이콘 변경',
    'agent.settings': '챗봇 설정',
    'agent.notification': '알림보내기',
    'agent.upload': '문서 업로드',
    'agent.performance': '성과 분석',
    'agent.help': '도움말',
    'agent.documentManagement': '문서 관리',
    'agent.active': '활성',
    'agent.chat': '에이전트 채팅',
    'agent.agentManagement': '에이전트 관리',
    'agent.functionsSelect': '기능선택',
    'agent.totalUsers': '총 메시지',
    'agent.satisfaction': '사용률',
    'agent.ranking': '순위',
    'agent.managementMode': '관리자 모드',
    'agent.generalChat': '채팅',
    
    // 카테고리
    'category.school': '학교',
    'category.professor': '교수',
    'category.student': '학생',
    'category.group': '그룹',
    'category.function': '기능형',
    
    // 시간 표시
    'time.recent': '최근',
    
    // 계정 설정
    'account.settings': '계정 설정',
    'account.lightMode': '라이트 모드',
    'account.logout': '로그아웃',
    
    // 대시보드 카드 설명
    'dashboard.activeUsersDesc': '활성 사용자: 12',
    'dashboard.activeAgentsDesc': '활성 에이전트: 79',
    'dashboard.totalMessagesDesc': '총 메시지: 145',
    'dashboard.weeklyGrowthDesc': '주간 성장률: +15.2%',
    'dashboard.todayQuestionsPercent': '+12%',
    'dashboard.avgResponseTimeChange': '-0.3초',
    'dashboard.responseSuccessPercent': '전월 대비',
    'dashboard.userSatisfactionDesc': '향상 중',
    'dashboard.tokenUsageDailyPercent': '+12% 지난 주 대비',
    'dashboard.estimatedCostDesc': '이번 달 예상 비용',
    'account.noInfo': '정보 없음',
    'account.student': '학생',
    'account.faculty': '교직원',
    'account.admin': '관리자',
    
    // 파일 관리
    'files.uploadedFiles': '업로드된 파일',
    'files.size': '크기',
    'files.uploadDate': '업로드',
    'files.uploadTime': '업로드일',
    'files.noFiles': '업로드된 파일이 없습니다',
    
    // 대시보드 카드
    'dashboard.todayQuestions': '오늘 질문 수',
    'dashboard.avgResponseTime': '평균 응답 시간',
    'dashboard.responseSuccess': '질문 응답 성공률',
    'dashboard.userSatisfaction': '응답 사용자 만족도',
    'dashboard.tokenUsageDaily': '토큰 소비량 일평균',
    'dashboard.estimatedCost': '토큰 예상 비용',
    'dashboard.popularQuestions': '인기 질문 TOP 5',
    'dashboard.systemStatus': 'System Status',
    'dashboard.database': 'Database',
    'dashboard.openaiApi': 'OpenAI API',
    'dashboard.sessionStore': 'Session Store',
    'dashboard.fileUpload': 'File Upload',
    'dashboard.healthy': 'Healthy',
    
    // Chat interface
    'chat.typing': '메시지 작성 중...',
    'chat.inputPlaceholder': '메시지를 입력하세요...',
    'chat.agentGreeting': '안녕하세요! 저는 {{name}}입니다. 궁금한 것이 있으면 언제든지 물어보세요.',
    
    // Management interface
    'management.personaTitle': '페르소나',
    'management.personaDesc': '에이전트 성격 및 말투 설정',
    'chat.deleteHistory': '채팅 기록 삭제',
    
    // 마스터 관리자 센터
    'admin.title': 'LoBo AI 관리자 센터',
    'admin.subtitle': '대학교 AI 챗봇 서비스 통합 관리',
    'admin.dashboard': '대시보드',
    'admin.categories': '조직 카테고리 관리',
    'admin.users': '사용자 관리',
    'admin.agents': '에이전트 관리',
    'admin.documents': '문서 관리',
    'admin.conversations': '질문/응답 로그',
    'admin.tokens': '토큰 관리',
    'admin.system': '시스템 설정',
    'admin.logout': '로그아웃',
    'admin.chatbot': 'LoBo 챗봇',
    'admin.totalUsers': '총 사용자',
    'admin.totalAgents': '총 에이전트',
    'admin.totalConversations': '총 대화',
    'admin.totalTokens': '총 토큰',
    'admin.todayActivity': '오늘 활동',
    'admin.systemStatus': '시스템 상태',
    'admin.activeUsers': '활성 사용자',
    'admin.activeAgents': '활성 에이전트',
    'admin.totalMessages': '총 메시지',
    'admin.weeklyGrowth': '주간 증가율',
    'admin.recentActivity': '최근 활동',
    'admin.database': '데이터베이스',
    'admin.openaiApi': 'OpenAI API',
    'admin.sessionStore': '세션 스토어',
    'admin.fileUpload': '파일 업로드',
    'admin.status.healthy': '정상',
    'admin.status.error': '오류',
    'admin.organizationManagement': '조직 카테고리 관리',
    'admin.userManagement': '사용자 관리',
    'admin.agentManagement': '에이전트 관리',
    'admin.documentManagement': '문서 관리',
    'admin.qaLogs': '질문/응답 로그',
    'admin.tokenManagement': '토큰 관리',
    'admin.systemSettings': '시스템 설정',
    'admin.todayQuestionsTitle': '오늘 질문 수',
    'admin.avgResponseTimeTitle': '평균 응답 시간',
    'admin.responseFailureTitle': '응답 실패율',
    'admin.userSatisfactionTitle': '사용자 만족도',
    'admin.userSearch': '사용자 검색',
    'admin.organizationSearch': '조직 검색 및 관리',
    'admin.agentSearch': '에이전트 검색 및 관리',
    'admin.filterByOrganization': '필터 초기화',
    'admin.search': '검색',
    'admin.download': '다운로드',
    
    // Navigation mobile
    'nav.organizations': '조직',
    'nav.users': '사용자',
    'nav.agents': '에이전트',
    'nav.documents': '문서',
    'nav.qa': '질문 응답',
    'nav.tokens': '토큰',
    'admin.addUser': '사용자 추가',
    'admin.addOrganization': '새 조직 카테고리 추가',
    'admin.lmsSync': 'LMS 연동 (권장)',
    'admin.fileUploadDesc': '파일 업로드',
    'admin.organizationList': '조직 목록',
    
    // Organization Management
    'org.lmsIntegration': 'LMS 연동 (권장)',
    'org.fileUpload': '파일 업로드',
    'org.categorySearchManagement': '조직 카테고리 검색 및 관리',
    'org.upperOrganization': '상위조직',
    'org.all': '전체',
    'org.lowerOrganization': '하위조직',
    'org.detailOrganization': '세부조직',
    'org.resetFilters': '필터 초기화',
    'org.organizationList': '조직 목록',
    'org.totalOrganizations': '전체 124개 조직 중 1-20개 표시',
    'org.upperOrg': '상위 조직',
    'org.lowerOrg': '하위 조직',
    'org.detailOrg': '세부 조직',
    'org.manager': '관리자',
    'org.memberCount': '소속 인원',
    'org.agentCount': '에이전트 수',
    'org.status': '상태',
    'org.select': '선택',
    'admin.userList': '사용자 목록',
    'admin.select': '선택',
    'admin.none': '선택 안함',
    'admin.selected': '명 선택됨',
    'admin.lightMode': '라이트 모드',
    'admin.agentDownloadSuccess': '에이전트 목록이 Excel 파일로 다운로드되었습니다.',
    'admin.agentDownloadFailed': 'Excel 파일 다운로드에 실패했습니다.',
    'admin.downloadSuccess': '다운로드 완료',
    'admin.downloadFailed': '다운로드 실패',
    'admin.downloadDescription': '파일이 다운로드되었습니다.',
    'admin.downloadError': '다운로드 중 오류가 발생했습니다.',
    
    // Document Management Korean
    'doc.fileType': '파일 형식',
    'doc.fileRequirements': '파일 형식 요구사항',
    'doc.inactiveFiles': '비활성 문서',
    'doc.totalCapacity': '총 용량',
    'doc.others': '기타',
    'doc.resetFilters': '필터 초기화',
    'doc.searchResults': '검색 결과',
    'doc.searchKeyword': '검색어',

    // Organization Management - Unified Keys  
    'org.searchAndManagement': '조직 카테고리 검색 및 관리',
    'org.upperCategory': '상위 조직 카테고리',
    'org.lowerCategory': '하위 조직 카테고리', 
    'org.detailCategory': '세부 조직 카테고리',
    'org.selectOption': '선택',
    'org.searchByName': '조직명으로 검색하세요.',
    'org.lmsIntegrationRecommended': 'LMS 연동 (권장)',
    'org.lmsIntegrationDesc': '대학 LMS 시스템과 연동하여 조직 구조를 자동으로 동기화합니다.',
    'org.fileUploadAction': '파일 업로드',
    'org.fileUploadDesc': 'CSV/Excel 파일을 업로드하여 조직 구조를 일괄 등록합니다.',
    'org.addNewCategoryManual': '새 조직 수동 추가',
    'org.addNewCategoryDesc': '개별 조직을 수동으로 생성하고 설정합니다.',
    'org.resetFilters': '필터 초기화',
    
    // Q&A and Token Management
    'admin.qaManagement': 'Q&A 관리',
    'admin.todayQuestions': '247',
    'admin.avgResponseTime': '2.3초',
    'admin.responseSuccessTitle': '질문 응답 성공률',
    'admin.dailyImprovement': '전일 대비 향상',
    'admin.improving': '향상 중',
    'admin.tokenDailyAvgTitle': '토큰 소비량 일일 평균',
    'admin.weeklyCompared': '+12% 지난 주 대비',
    'admin.tokenEstimatedCostTitle': '토큰 예상 비용',
    'admin.monthlyEstimated': '이번 달 예상 비용',
    'admin.popularQuestionsTop5': '인기 질문 TOP 5',
    'admin.loading': '로딩 중...',
    'admin.dataLoadError': '데이터를 불러올 수 없습니다',
    'admin.times': '회',
    'admin.noQuestionData': '질문 데이터가 없습니다',
    'admin.responseSuccess': '96.8%',
    'admin.userSatisfactionValue': '4.6/5',
    'admin.dailyAverageTitle': '토큰 소비량 일평균',
    'admin.dailyAverage': '2.6K',
    'admin.estimatedCostTitle': '토큰 예상 비용',
    'admin.estimatedCost': '₩6,761',
    'admin.inputAverageTitle': '토큰 투입량 평균',
    'admin.inputAverage': '73%',
    'admin.popularQuestionsTitle': '인기 질문 TOP 5',
    'admin.systemStatusTitle': 'System Status',
    
    // Q&A Logs specific
    'admin.userType': '사용자 유형',
    'admin.period': '기간',
    'admin.questionSearch': '질문 내용으로 검색하세요.',
    'admin.responseMethod': '응답 방식',
    'admin.responseFail': '응답 실패',
    'admin.improvementRequest': '개선 요청',
    'admin.organizationAffiliation': '조직 소속',
    'admin.question': '질문',
    'admin.answer': '답변',
    'admin.responseTime': '응답 시간',
    'admin.time': '시간',
    'admin.organization': '소속 조직',
    'admin.conversationTime': '대화 시각',
    'admin.agent': '에이전트',
    'admin.responseStatus': '응답 상태',
    'admin.questionContent': '질문 내용',
    'admin.responseContent': '응답 내용',
    'admin.improveComment': '개선 요청 코멘트',
    'admin.improveCommentPlaceholder': '개선이 필요한 내용을 입력해주세요.',
    'admin.success': '성공',
    'admin.failure': '실패',
    'admin.like': '좋아요',
    'admin.dislike': '싫어요',
    'admin.unknown': '알 수 없음',
    'admin.noQuestionContent': '질문 내용이 없습니다',
    'admin.noResponseContent': '응답 내용이 없습니다',
    'admin.improveRequestTitle': '개선 요청 및 코멘트',
    'admin.improveRequestDesc': '질의응답에 대한 개선 요청과 코멘트를 작성합니다.',
    'admin.questionAnswerDetailTitle': '질문응답 상세보기',
    'admin.questionAnswerDetailDesc': '질의응답 세부 정보를 확인합니다.',
    
    // 언어 이름
    'language.ko': '한국어',
    'language.en': 'English',
    
    // 조직 카테고리 관리 - 액션 카드
    'org.lmsIntegrationRecommended': 'LMS 연동 (권장)',
    'org.lmsIntegrationDesc': '대학 LMS 시스템과 연동하여 사용자 정보를 자동으로 동기화합니다.',
    'org.fileUploadAction': '파일 업로드',
    'org.fileUploadDesc': 'CSV/Excel 파일을 업로드하여 조직 구조를 일괄 등록합니다.',
    'org.addNewCategoryManual': '새 조직 수동 추가',
    'org.categorySearch': '조직 카테고리 검색',
    'org.upperCategory': '상위 조직 카테고리',
    'org.lowerCategory': '하위 조직 카테고리',
    'org.detailCategory': '세부 조직 카테고리',
    'org.selectOption': '선택',
    'org.selectUpper': '상위 조직 선택',
    'org.selectLower': '하위 조직 선택',
    'org.selectDetail': '세부 조직 선택',
    'org.searchByName': '조직명으로 검색하세요.',
    'org.searchAndManagement': '조직 카테고리 검색 및 관리',
    'org.resetFilters': '필터 초기화',
    'org.all': '전체',
    'org.addNewCategoryDesc': '새로운 조직 카테고리를 직접 생성하고 설정합니다.',
    'org.organizationList': '조직 목록',
    'org.totalOrganizations': '전체 124개 조직 중 1-20개 표시',
    
    // 사용자 관리 - 액션 카드  
    'user.lmsIntegrationRecommended': 'LMS 연동 (권장)',
    'user.lmsIntegrationDesc': '대학 LMS 시스템과 연동하여 사용자 정보를 자동으로 동기화합니다.',
    'user.fileUploadAction': '파일 업로드', 
    'user.fileUploadDesc': 'CSV/Excel 파일을 업로드하여 다수의 사용자를 일괄 등록합니다.',
    'user.addNewUser': '사용자 수동 추가',
    'user.addNewUserDesc': '새로운 사용자를 직접 생성하고 설정합니다.',
    'user.userSearch': '사용자 검색',
    'user.downloadUserList': '사용자 목록 다운로드',
    
    // Agent Management
    'agent.addNewAgent': '에이전트 수동 추가',
    'agent.addNewAgentDesc': '새로운 에이전트를 직접 생성하고 설정합니다.',
    'agent.fileUploadAction': '파일 업로드',
    'agent.fileUploadDesc': 'CSV/Excel 파일을 업로드하여 다수의 에이전트를 일괄 등록합니다.',
    'agent.agentSearch': '에이전트 검색',
    'agent.type': '유형',
    'agent.status': '상태',
    'agent.searchByName': '에이전트명 또는 설명 키워드를 입력하세요',
    'agent.agentList': '에이전트 목록',
    'agent.totalAgents': '전체 100개 중 1-15개 표시',
    'agent.name': '에이전트명',
    'agent.manager': '관리자',
    'agent.affiliation': '소속',
    'agent.documents': '문서',
    'agent.settings': '설정',
    'agent.active': '활성',
    'agent.inactive': '비활성',
    'agent.basicInfo': '기본 정보',
    'agent.persona': '페르소나',
    'agent.modelSettings': '모델 설정',
    'agent.fileUpload': '파일 업로드',
    'agent.managerSelection': '관리자 선정',
    'agent.sharingSettings': '공유 설정',
    'agent.description': '에이전트 설명',
    'agent.descriptionPlaceholder': '에이전트의 역할과 기능을 설명해주세요 (최대 200자)',
    'agent.rolePrompt': '역할/프롬프트',
    'agent.rolePromptPlaceholder': '예: 대학원 논문 첨삭 도우미, 학과 정보 안내 봇',
    'agent.selectType': '유형 선택',
    'agent.school': '학교',
    'agent.professor': '교수',
    'agent.student': '학생',
    'agent.group': '그룹',
    'agent.functional': '기능형',
    'agent.organization': '소속',
    'agent.nickname': '닉네임',
    'agent.nicknamePlaceholder': '예: 민지, 교수님 어시스턴트',
    'agent.speechStyle': '말투 스타일',
    'agent.speechStylePlaceholder': '예: 공손하고 친절한 말투로 대화합니다',
    'agent.expertiseArea': '지식/전문 분야',
    'agent.expertiseAreaPlaceholder': '예: 컴퓨터공학, 프로그래밍, 학사업무, 입학상담 등',
    'agent.personality': '성격특성',
    'agent.personalityPlaceholder': '예: 친절하고 도움이 되는 성격, 논리적 사고, 인내심 있음',
    'agent.forbiddenResponse': '금칙어 반응 방식',
    'agent.forbiddenResponsePlaceholder': '예: 죄송하지만 해당 질문에 대해서는 답변드릴 수 없습니다. 다른 주제로 대화해주세요.',
    'agent.llmModel': '사용 LLM 모델',
    'agent.responseMethod': '응답 방식',
    'agent.docPriorityLLM': '문서 우선 + LLM',
    'agent.llmPriority': 'LLM 우선',
    'agent.docOnly': '문서 only',
    'agent.maxInputLength': '최대 입력 글자 수',
    'agent.maxOutputLength': '최대 응답 글자 수',
    'agent.maxTwentyChars': '최대 20자',
    'agent.createNewAgent': '새 에이전트 생성',
    'agent.downloadAgentList': '에이전트 목록 다운로드',
    'common.characters': '자',
    'common.downloading': '다운로드 중...',
    
    // Document Management
    'doc.lmsIntegrationRecommended': 'LMS 연동 (권장)',
    'doc.lmsIntegrationDesc': 'LMS 시스템에서 각종 자료 및 문서를 자동으로 가져옵니다.',
    'doc.directUpload': '직접 업로드',
    'doc.directUploadDesc': 'PDF, Word, Excel 파일을 직접 업로드하여 관리합니다.',
    'doc.totalDocuments': '전체 파일 수',
    'doc.inactiveDocuments': '비활성 문서 수',
    'doc.totalCapacity': '총 용량',
    'doc.documentSearch': '문서 검색',
    'doc.documentType': '문서 종류',
    'doc.fileType': '파일 형식',
    'doc.uploadDate': '업로드 날짜',
    'doc.searchByContent': '문서명 또는 내용으로 검색하세요.',
    'doc.documentList': '문서 목록',
    'doc.totalDocumentsCount': '전체 20개 중 1-15개 표시',
    'doc.fileName': '파일명',
    'doc.type': '종류',
    'doc.size': '크기',
    'doc.uploadedDate': '업로드 날짜',
    'doc.connectedAgent': '연결된 에이전트',
    'doc.searchKeyword': '검색어',
    
    // Q&A Management
    'qa.logs': '로그 검색',
    'qa.userType': '사용자 유형',
    'qa.period': '기간',
    'qa.searchByQuestion': '질문 내용으로 검색하세요.',
    'qa.qaList': '질문 응답 목록',
    'qa.totalQACount': '전체 6개 중 1-6개 표시',
    'qa.agent': '에이전트',
    'qa.question': '질문',
    'qa.responseMethod': '응답 방식',
    'qa.responseSuccess': '응답 성공',
    'qa.responseTime': '응답 시간',
    'qa.time': '시간',
    
    // Token Management
    'token.dailyUsage': '일간 사용량',
    'token.dailyAverage': '일일 평균',
    'token.estimatedCost': '예상 비용',
    'token.organizationSearch': 'Organization Search',
    'token.tokenUsageList': '토큰 사용량 목록',
    'token.totalTokenCount': '전체 토큰 사용 기록',
    'token.agent': '에이전트',
    'token.question': '질문',
    'token.input': '입력',
    'token.output': '출력',
    'token.reading': '색인',
    'token.documentProcessing': '문서 전처리',
    'token.total': '총합',
    
    // Agent File Upload
    'agent.documentType': '문서 유형',
    'agent.documentManual': '매뉴얼/가이드',
    'agent.documentFAQ': 'FAQ/질답',
    'agent.documentPolicy': '정책/규정',
    'agent.documentProcedure': '절차/프로세스',
    'agent.documentReference': '참고자료',
    'agent.documentCourse': '강의자료',
    'agent.documentResearch': '연구자료',
    'agent.documentOther': '기타',
    'agent.dragOrClick': '파일을 여기로 드래그하거나 클릭해서 업로드하세요',
    'agent.selectFile': '파일 선택',
    'agent.supportedFormats': '지원 형식: PDF, DOC, DOCX, TXT, PPT, PPTX',
    'agent.maxSize': '최대 크기: 50MB',
    'agent.selectedFiles': '선택된 파일',
    'agent.noFilesSelected': '아직 선택된 파일이 없습니다',
    'agent.visibility': '공개 범위',
    'agent.publicVisibility': '전체 공개',
    'agent.organizationVisibility': '조직 내 공개',
    'agent.privateVisibility': '비공개',
    
    // Navigation tabs
    'nav.dashboard': '대시보드',
    'nav.organizations': '조직',
    'nav.users': '사용자',
    'nav.agents': '에이전트',
    'nav.documents': '문서',
    'nav.qa': '질문응답',
    'nav.tokens': '토큰',
    'nav.settings': '설정',
  },
  
  en: {
    // Login page
    'auth.title': 'LoBo',
    'auth.subtitle': 'University AI Chatbot System',
    'auth.login': 'Login',
    'auth.username': 'Student/Faculty ID',
    'auth.usernamePlaceholder': 'e.g: 2024001234 or F2024001',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.forgotPasswordMessage': 'Contact administrator to reset your password.',
    'auth.loginButton': 'Login',
    'auth.loggingIn': 'Logging in...',
    'auth.demoAccounts': 'Quick login with demo accounts',
    'auth.studentAccount': '👨‍🎓 Student Account',
    'auth.facultyAccount': '👨‍🏫 Faculty Account',
    'auth.masterAccount': '🔑 Master Account',
    'auth.adminSystem': 'Admin System',
    'auth.demoStudentDesc': 'Jang Jihoon (user1082) - College of Liberal Arts / Korean Literature / Modern Literature, Student',
    'auth.demoFacultyDesc': 'Jung Subin (user1081) - College of Liberal Arts / Korean Literature / Modern Literature, Professor, Agent Manager',
    'auth.demoMasterDesc': 'Master Admin (master_admin) - LoBo AI Chatbot Integrated Management Center Access',
    'auth.autoCreate': 'Account will be created automatically if not exists',
    'auth.loginSuccess': 'Login Successful',
    'auth.welcome': 'Welcome!',
    'auth.loginFailed': 'Login Failed',
    'auth.loginError': 'Please check your ID or password.',
    'auth.settings': 'Settings',
    'auth.themeSettings': 'Theme Settings',
    'auth.languageSettings': 'Language Settings',
    'auth.usernameRequired': 'Please enter your ID',
    'auth.passwordRequired': 'Please enter password',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.firstNameRequired': 'Please enter first name',
    'auth.lastNameRequired': 'Please enter last name',
    'auth.emailInvalid': 'Please enter a valid email address',
    
    // Common UI elements
    'common.home': 'Home',
    'common.chat': 'Chat',
    'common.management': 'Management',
    'common.logout': 'Logout',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.files': 'Files',
    'common.settings': 'Settings',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Organization Management
    'org.lmsIntegration': 'LMS Integration (Recommended)',
    'org.fileUpload': 'File Upload',
    'org.categorySearchManagement': 'Organization Category Search & Management',
    'org.upperOrganization': 'Upper Organization',
    'org.all': 'All',
    'org.lowerOrganization': 'Lower Organization',
    'org.detailOrganization': 'Detail Organization',
    'org.organizationList': 'Organization List',
    'org.totalOrganizations': 'Showing 1-20 of 124 total organizations',
    'org.upperOrg': 'Upper Organization',
    'org.lowerOrg': 'Lower Organization',
    'org.detailOrg': 'Detail Organization',
    'org.manager': 'Manager',
    'org.memberCount': 'Member Count',
    'org.agentCount': 'Agent Count',
    'org.status': 'Status',
    'org.select': 'Select',

    // Homepage
    'home.searchPlaceholder': 'Search agents...',
    'home.categories.all': 'All',
    'home.categories.school': 'School',
    'home.categories.professor': 'Professor',
    'home.categories.student': 'Student',
    'home.categories.group': 'Group',
    'home.categories.function': 'Function',
    'home.accountSettings': 'Account Settings',
    'account.regularUser': 'Regular User',
    'account.agentManager': 'Agent Manager',
    'account.masterAdmin': 'Master Admin',
    'account.operationManager': 'Operation Manager',
    'account.categoryManager': 'Category Manager',
    'account.qaManager': 'QA Manager',
    'account.documentManager': 'Document Manager',
    'account.externalUser': 'External User',
    'account.active': 'Active',
    'account.inactive': 'Inactive',
    'account.locked': 'Locked',
    'account.pending': 'Pending',
    'account.unknown': 'Unknown',
    'file.validate': 'Validate',
    'file.overwrite': 'Overwrite',
    'file.add': 'Add',
    'file.uploadComplete': 'File {action} Complete',
    'file.uploadSuccess': 'File has been successfully {action}ed.',
    'file.deleteComplete': 'Delete Complete',
    'file.deleteSuccess': 'File has been successfully deleted.',
    'file.deleteFailed': 'Delete Failed',
    'file.deleteError': 'Failed to delete file.',
    'file.unsupportedFormat': 'Unsupported File Format',
    'file.formatRequirement': 'Only Excel(.xlsx, .xls) or CSV(.csv) files can be uploaded.',
    'file.sizeExceeded': 'File Size Exceeded',
    'file.sizeLimit': 'Only files under 50MB can be uploaded.',
    'file.downloadFailed': 'Download Failed',
    'file.downloadError': 'Failed to download sample file.',
    'file.sampleFileName': 'user_upload_sample.xlsx',
    'home.selectAgent': 'Select an agent',
    'home.selectAgentDesc': 'Choose an agent from the left to start chatting.',
    'home.manageAgent': 'Select an agent to manage',
    'home.manageAgentDesc': 'Choose an agent from the left to access management interface.',
    
    // Agent management
    'agent.management': 'Agent Management',
    'agent.managementDesc': 'Select a managed agent to configure settings',
    'agent.persona': 'Persona Change',
    'agent.iconChange': 'Change Icon',
    'agent.settings': 'Bot Settings',
    'agent.notification': 'Send Notification',
    'agent.upload': 'Upload Document',
    'agent.performance': 'Performance Analysis',
    'agent.help': 'Help',
    'agent.documentManagement': 'Document Management',
    'agent.active': 'Active',
    'agent.chat': 'Agent Chat',
    'agent.agentManagement': 'Agent Management',
    'agent.functionsSelect': 'Functions',
    'agent.totalUsers': 'Total Messages',
    'agent.satisfaction': 'Usage Rate',
    'agent.ranking': 'Ranking',
    'agent.managementMode': 'Management Mode',
    'agent.generalChat': 'General Chat',
    
    // Categories
    'category.school': 'School',
    'category.professor': 'Professor',
    'category.student': 'Student',
    'category.group': 'Group',
    'category.function': 'Function',
    
    // Time display
    'time.recent': 'Recent',
    
    // Account Settings
    'account.settings': 'Account Settings',
    'account.lightMode': 'Light Mode',
    'account.logout': 'Logout',
    
    // Dashboard card descriptions
    'dashboard.activeUsersDesc': 'Active Users: 12',
    'dashboard.activeAgentsDesc': 'Active Agents: 79',
    'dashboard.totalMessagesDesc': 'Total Messages: 145',
    'dashboard.weeklyGrowthDesc': 'Weekly Growth: +15.2%',
    'dashboard.todayQuestionsPercent': '+12%',
    'dashboard.avgResponseTimeChange': '-0.3s',
    'dashboard.responseSuccessPercent': 'vs Last Month',
    'dashboard.userSatisfactionDesc': 'Improving',
    'dashboard.tokenUsageDailyPercent': '+12% vs Last Week',
    'dashboard.estimatedCostDesc': 'This Month Estimate',
    'account.noInfo': 'No information',
    'account.student': 'Student',
    'account.faculty': 'Faculty',
    'account.admin': 'Administrator',
    
    // File Management
    'files.uploadedFiles': 'Uploaded Files',
    'files.size': 'Size',
    'files.uploadDate': 'Upload',
    'files.uploadTime': 'Upload Date',
    'files.noFiles': 'No uploaded files',
    
    // Dashboard Cards
    'dashboard.todayQuestions': 'Today\'s Questions',
    'dashboard.avgResponseTime': 'Average Response Time',
    'dashboard.responseSuccess': 'Response Success Rate',
    'dashboard.userSatisfaction': 'User Satisfaction',
    'dashboard.tokenUsageDaily': 'Daily Token Usage',
    'dashboard.estimatedCost': 'Estimated Token Cost',
    'dashboard.popularQuestions': 'Popular Questions TOP 5',
    'dashboard.systemStatus': 'System Status',
    'dashboard.database': 'Database',
    'dashboard.openaiApi': 'OpenAI API',
    'dashboard.sessionStore': 'Session Store',
    'dashboard.fileUpload': 'File Upload',
    'dashboard.healthy': 'Healthy',
    
    // Chat interface
    'chat.typing': 'Typing...',
    'chat.inputPlaceholder': 'Type a message...',
    'chat.agentGreeting': 'Hello! I am {{name}}. Feel free to ask me anything anytime.',
    
    // Management interface
    'management.personaTitle': 'Persona',
    'management.personaDesc': 'Set agent personality and speaking style',
    'chat.deleteHistory': 'Delete Chat History',
    
    // Document Management
    'doc.management': 'Document Management',
    'doc.lmsConnected': 'LMS Connected',
    'doc.lmsDescription': 'LMS system allows automatic document and content import.',
    'doc.directUpload': 'Direct Upload',
    'doc.directUploadDescription': 'PDF, Word, Excel files can be uploaded directly.',
    'doc.statistics': 'Document Statistics',
    'doc.searchAndManagement': 'Document Search & Management',
    'doc.totalFiles': 'Total Files',
    'doc.wordFiles': 'Word Files',
    'doc.excelFiles': 'Excel Files',
    'doc.pdfFiles': 'PDF Files',
    'doc.etc': 'Other',
    'doc.totalSize': 'Total Size',
    'doc.recentUploads': 'Recent Uploads',
    'doc.fileName': 'File Name',
    'doc.category': 'Category',
    'doc.manager': 'Manager',
    'doc.uploadDate': 'Upload Date',
    'doc.searchPlaceholder': 'Search by file name, category, manager...',
    'doc.search': 'Search',
    'doc.fileType': 'File Type',
    'doc.fileRequirements': 'File Format Requirements',
    'doc.inactiveFiles': 'Inactive Documents',
    'doc.totalCapacity': 'Total Capacity',
    'doc.others': 'Others',
    'doc.resetFilters': 'Reset Filters',
    'doc.searchResults': 'Search Results: {count} documents',
    'doc.searchKeyword': 'Search Keyword',

    // Organization Management
    'org.searchAndManagement': 'Organization Category Search & Management',
    'org.upperCategory': 'Upper Organization',
    'org.lowerCategory': 'Lower Organization', 
    'org.detailCategory': 'Detail Organization',
    'org.organizationSearch': 'Organization Search',
    'org.searchPlaceholder': 'Search by organization name...',

    // Master Admin Center
    'admin.title': 'LoBo AI Admin Center',
    'admin.subtitle': 'University AI Chatbot Service Integrated Management',
    'admin.dashboard': 'Dashboard',
    'admin.categories': 'Organization Category Management',
    'admin.users': 'User Management',
    'admin.agents': 'Agent Management',
    'admin.documents': 'Document Management',
    'admin.conversations': 'Q&A Logs',
    'admin.tokens': 'Token Management',
    'admin.system': 'System Settings',
    'admin.logout': 'Logout',
    'admin.chatbot': 'LoBo Chatbot',
    'admin.totalUsers': 'Total Users',
    'admin.totalAgents': 'Total Agents',
    'admin.totalConversations': 'Total Conversations',
    'admin.totalTokens': 'Total Tokens',
    'admin.todayActivity': 'Today\'s Activity',
    'admin.systemStatus': 'System Status',
    'admin.activeUsers': 'Active Users',
    'admin.activeAgents': 'Active Agents',
    'admin.totalMessages': 'Total Messages',
    'admin.weeklyGrowth': 'Weekly Growth',
    'admin.recentActivity': 'Recent Activity',
    'admin.database': 'Database',
    'admin.openaiApi': 'OpenAI API',
    'admin.sessionStore': 'Session Store',
    'admin.fileUpload': 'File Upload',
    'admin.status.healthy': 'Healthy',
    'admin.status.error': 'Error',
    'admin.organizationManagement': 'Organization Category Management',
    'admin.userManagement': 'User Management',
    'admin.agentManagement': 'Agent Management',
    'admin.documentManagement': 'Document Management',
    'admin.qaLogs': 'Q&A Logs',
    'admin.tokenManagement': 'Token Management',
    'admin.systemSettings': 'System Settings',
    'admin.todayQuestionsTitle': 'Today\'s Questions',
    'admin.avgResponseTimeTitle': 'Avg Response Time',
    'admin.responseFailureTitle': 'Response Failure Rate',
    'admin.userSatisfactionTitle': 'User Satisfaction',
    'admin.userSearch': 'User Search',
    'admin.organizationSearch': 'Organization Search & Management',
    'admin.agentSearch': 'Agent Search & Management',
    'admin.filterByOrganization': 'Reset Filters',
    'admin.search': 'Search',
    'admin.download': 'Download',
    'admin.addUser': 'Add User',
    'admin.addOrganization': 'Add New Organization Category',
    'admin.lmsSync': 'LMS Integration (Recommended)',
    'admin.fileUploadDesc': 'File Upload',
    'admin.organizationList': 'Organization List',
    'admin.userList': 'User List',
    'admin.select': 'Select',
    'admin.none': 'None',
    'admin.selected': ' selected',
    'admin.lightMode': 'Light Mode',
    'admin.agentDownloadSuccess': 'Agent list has been downloaded as Excel file.',
    'admin.agentDownloadFailed': 'Failed to download Excel file.',
    'admin.downloadSuccess': 'Download Complete',
    'admin.downloadFailed': 'Download Failed',
    'admin.downloadDescription': 'File has been downloaded.',
    'admin.downloadError': 'An error occurred during download.',
    
    // Q&A and Token Management English
    'admin.qaManagement': 'Q&A Management',
    'admin.todayQuestions': '247',
    'admin.avgResponseTime': '2.3s',
    'admin.responseSuccessTitle': 'Response Success Rate',
    'admin.dailyImprovement': 'Daily Improvement',
    'admin.improving': 'Improving',
    'admin.tokenDailyAvgTitle': 'Daily Token Usage Average',
    'admin.weeklyCompared': '+12% compared to last week',
    'admin.tokenEstimatedCostTitle': 'Token Estimated Cost',
    'admin.monthlyEstimated': 'Monthly Estimated Cost',
    'admin.popularQuestionsTop5': 'Popular Questions TOP 5',
    'admin.loading': 'Loading...',
    'admin.dataLoadError': 'Unable to load data',
    'admin.times': 'times',
    'admin.noQuestionData': 'No question data available',
    'admin.responseSuccess': '96.8%',
    'admin.userSatisfactionValue': '4.6/5',
    'admin.dailyAverageTitle': 'Daily Token Usage',
    'admin.dailyAverage': '2.6K',
    'admin.estimatedCostTitle': 'Estimated Token Cost',
    'admin.estimatedCost': '$6,761',
    'admin.inputAverageTitle': 'Input Token Average',
    'admin.inputAverage': '73%',
    'admin.popularQuestionsTitle': 'Popular Questions TOP 5',
    'admin.systemStatusTitle': 'System Status',
    
    // Q&A Logs specific English
    'admin.userType': 'User Type',
    'admin.period': 'Period',
    'admin.questionSearch': 'Search by question content...',
    'admin.responseMethod': 'Response Method',
    'admin.responseFail': 'Response Failed',
    'admin.improvementRequest': 'Improvement Request',
    'admin.organizationAffiliation': 'Organization',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.responseTime': 'Response Time',
    'admin.time': 'Time',
    'admin.organization': 'Organization',
    'admin.conversationTime': 'Conversation Time',
    'admin.agent': 'Agent',
    'admin.responseStatus': 'Response Status',
    'admin.questionContent': 'Question Content',
    'admin.responseContent': 'Response Content',
    'admin.improveComment': 'Improvement Comment',
    'admin.improveCommentPlaceholder': 'Enter content that needs improvement...',
    'admin.success': 'Success',
    'admin.failure': 'Failed',
    'admin.like': 'Like',
    'admin.dislike': 'Dislike',
    'admin.unknown': 'Unknown',
    'admin.noQuestionContent': 'No question content available',
    'admin.noResponseContent': 'No response content available',
    'admin.improveRequestTitle': 'Improvement Request & Comment',
    'admin.improveRequestDesc': 'Write improvement requests and comments for Q&A.',
    'admin.questionAnswerDetailTitle': 'Question & Answer Details',
    'admin.questionAnswerDetailDesc': 'View detailed Q&A information.',
    
    // Language names
    'language.ko': '한국어',
    'language.en': 'English',
    
    // Organization Category Management - Action Cards
    'org.lmsIntegrationRecommended': 'LMS Integration (Recommended)',
    'org.lmsIntegrationDesc': 'Synchronize user information automatically by integrating with university LMS system.',
    'org.fileUploadAction': 'File Upload',
    'org.fileUploadDesc': 'Upload CSV/Excel files to batch register organization structure.',
    'org.addNewCategoryManual': 'Add New Organization Manually',
    'org.categorySearch': 'Organization Category Search',
    'org.upperCategory': 'Upper Organization Category',
    'org.lowerCategory': 'Lower Organization Category',
    'org.detailCategory': 'Detail Organization Category',
    'org.selectOption': 'Select',
    'org.selectUpper': 'Select Upper Organization',
    'org.selectLower': 'Select Lower Organization',
    'org.selectDetail': 'Select Detail Organization',
    'org.searchByName': 'Search by organization name...',
    'org.searchAndManagement': 'Organization Category Search and Management',
    'org.resetFilters': 'Reset Filters',
    'org.all': 'All',
    'org.addNewCategoryDesc': 'Create and configure new organization categories directly.',
    'org.organizationList': 'Organization List',
    'org.totalOrganizations': 'Showing 1-20 of 124 organizations',
    
    // User Management - Action Cards
    'user.lmsIntegrationRecommended': 'LMS Integration (Recommended)',
    'user.lmsIntegrationDesc': 'Synchronize user information automatically by integrating with university LMS system.',
    'user.fileUploadAction': 'File Upload',
    'user.fileUploadDesc': 'Upload CSV/Excel files to batch register multiple users.',
    'user.addNewUser': 'Add New User Manually',
    'user.addNewUserDesc': 'Create and configure new users directly.',
    'user.userSearch': 'User Search',
    'user.downloadUserList': 'Download User List',
    
    // Agent Management
    'agent.addNewAgent': 'Add New Agent Manually',
    'agent.addNewAgentDesc': 'Create and configure new agents directly.',
    'agent.fileUploadAction': 'File Upload',
    'agent.fileUploadDesc': 'Upload CSV/Excel files to batch register multiple agents.',
    'agent.agentSearch': 'Agent Search',
    'agent.type': 'Type',
    'agent.status': 'Status',
    'agent.searchByName': 'Enter agent name or description keywords',
    'agent.agentList': 'Agent List',
    'agent.totalAgents': 'Showing 1-15 of 100 total',
    'agent.name': 'Agent Name',
    'agent.manager': 'Manager',
    'agent.affiliation': 'Affiliation',
    'agent.documents': 'Documents',
    'agent.settings': 'Settings',
    'agent.active': 'Active',
    'agent.inactive': 'Inactive',
    'agent.basicInfo': 'Basic Information',
    'agent.persona': 'Persona',
    'agent.modelSettings': 'Model Settings',
    'agent.fileUpload': 'File Upload',
    'agent.managerSelection': 'Manager Selection',
    'agent.sharingSettings': 'Sharing Settings',
    'agent.description': 'Agent Description',
    'agent.descriptionPlaceholder': 'Describe the agent\'s role and functions (max 200 characters)',
    'agent.rolePrompt': 'Role/Prompt',
    'agent.rolePromptPlaceholder': 'E.g., Graduate thesis editing assistant, department information guide bot',
    'agent.selectType': 'Select Type',
    'agent.school': 'School',
    'agent.professor': 'Professor',
    'agent.student': 'Student',
    'agent.group': 'Group',
    'agent.functional': 'Functional',
    'agent.organization': 'Organization',
    'agent.nickname': 'Nickname',
    'agent.nicknamePlaceholder': 'E.g., Minji, Professor\'s Assistant',
    'agent.speechStyle': 'Speech Style',
    'agent.speechStylePlaceholder': 'E.g., Conversing in a polite and friendly manner',
    'agent.expertiseArea': 'Knowledge/Expertise Area',
    'agent.expertiseAreaPlaceholder': 'E.g., Computer engineering, programming, academic affairs, admissions counseling, etc.',
    'agent.personality': 'Personality Traits',
    'agent.personalityPlaceholder': 'E.g., Kind and helpful personality, logical thinking, patient',
    'agent.forbiddenResponse': 'Forbidden Response Method',
    'agent.forbiddenResponsePlaceholder': 'E.g., Sorry, I cannot answer that question. Please talk about another topic.',
    'agent.llmModel': 'LLM Model Used',
    'agent.responseMethod': 'Response Method',
    'agent.docPriorityLLM': 'Document Priority + LLM',
    'agent.llmPriority': 'LLM Priority',
    'agent.docOnly': 'Document Only',
    'agent.maxInputLength': 'Maximum Input Characters',
    'agent.maxOutputLength': 'Maximum Response Characters',
    'agent.maxTwentyChars': 'Maximum 20 characters',
    'agent.createNewAgent': 'Create New Agent',
    'agent.downloadAgentList': 'Download Agent List',
    'common.characters': ' characters',
    'common.downloading': 'Downloading...',
    
    // Document Management
    'doc.lmsIntegrationRecommended': 'LMS Integration (Recommended)',
    'doc.lmsIntegrationDesc': 'Automatically import materials and documents from LMS system.',
    'doc.directUpload': 'Direct Upload',
    'doc.directUploadDesc': 'Upload and manage PDF, Word, Excel files directly.',
    'doc.totalDocuments': 'Total Documents',
    'doc.inactiveDocuments': 'Inactive Documents',
    'doc.totalCapacity': 'Total Capacity',
    'doc.documentSearch': 'Document Search',
    'doc.documentType': 'Document Type',
    'doc.fileType': 'File Type',
    'doc.uploadDate': 'Upload Date',
    'doc.searchByContent': 'Search by document name or content...',
    'doc.documentList': 'Document List',
    'doc.totalDocumentsCount': 'Showing 1-15 of 20 total',
    'doc.fileName': 'File Name',
    'doc.type': 'Type',
    'doc.size': 'Size',
    'doc.uploadedDate': 'Upload Date',
    'doc.connectedAgent': 'Connected Agent',
    'doc.searchKeyword': 'Search Keyword',
    
    // Q&A Management
    'qa.logs': 'Log Search',
    'qa.userType': 'User Type',
    'qa.period': 'Period',
    'qa.searchByQuestion': 'Search by question content...',
    'qa.qaList': 'Q&A List',
    'qa.totalQACount': 'Showing 1-6 of 6 total',
    'qa.agent': 'Agent',
    'qa.question': 'Question',
    'qa.responseMethod': 'Response Method',
    'qa.responseSuccess': 'Response Success',
    'qa.responseTime': 'Response Time',
    'qa.time': 'Time',
    
    // Token Management
    'token.dailyUsage': 'Daily Usage',
    'token.dailyAverage': 'Daily Average',
    
    // Navigation mobile
    'nav.organizations': 'Organizations',
    'nav.users': 'Users',
    'nav.agents': 'Agents',
    'nav.documents': 'Documents',
    'nav.qa': 'Q&A',
    'nav.tokens': 'Tokens',
    'token.estimatedCost': 'Estimated Cost',
    'token.organizationSearch': 'Organization Search',
    'token.tokenUsageList': 'Token Usage List',
    'token.totalTokenCount': 'Total Token Usage Records',
    'token.agent': 'Agent',
    'token.question': 'Question',
    'token.input': 'Input',
    'token.output': 'Output',
    'token.reading': 'Index',
    'token.documentProcessing': 'Document Processing',
    'token.total': 'Total',
    
    // Agent File Upload
    'agent.documentType': 'Document Type',
    'agent.documentManual': 'Manual/Guide',
    'agent.documentFAQ': 'FAQ/Q&A',
    'agent.documentPolicy': 'Policy/Regulation',
    'agent.documentProcedure': 'Procedure/Process',
    'agent.documentReference': 'Reference Material',
    'agent.documentCourse': 'Course Material',
    'agent.documentResearch': 'Research Material',
    'agent.documentOther': 'Other',
    'agent.dragOrClick': 'Drag files here or click to upload',
    'agent.selectFile': 'Select File',
    'agent.supportedFormats': 'Supported formats: PDF, DOC, DOCX, TXT, PPT, PPTX',
    'agent.maxSize': 'Max size: 50MB',
    'agent.selectedFiles': 'Selected Files',
    'agent.noFilesSelected': 'No files selected yet',
    'agent.visibility': 'Visibility',
    'agent.publicVisibility': 'Public',
    'agent.organizationVisibility': 'Organization Only',
    'agent.privateVisibility': 'Private',
    
    // Navigation tabs
    'nav.dashboard': 'Dashboard',
    'nav.organizations': 'Organizations',
    'nav.users': 'Users',
    'nav.agents': 'Agents',
    'nav.documents': 'Documents',
    'nav.qa': 'Q&A',
    'nav.tokens': 'Tokens',
    'nav.settings': 'Settings',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>('ko');

  // 로컬 스토리지에서 언어 설정 로드
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // 언어 변경 시 로컬 스토리지에 저장
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  // 번역 함수
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
