import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'zh' | 'vi' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// 번역 데이터
const translations: Record<Language, Record<string, string>> = {
  ko: {
    // 로그인 페이지
    'auth.title': 'LoBo',
    'auth.subtitle': '대학교 AI 챗봇 시스템',
    'auth.login': '로그인',
    'auth.username': '학번/교번',
    'auth.usernamePlaceholder': '예: 2024001234 또는 F2024001',
    'auth.password': '비밀번호',
    'auth.passwordPlaceholder': '비밀번호를 입력하세요.',
    'auth.forgotPassword': '비밀번호를 잊으셨나요?',
    'auth.forgotPasswordMessage': '관리자에게 문의하여 비밀번호를 재설정해주세요.',
    'auth.loginButton': '로그인',
    'auth.loggingIn': '로그인 중...',
    'auth.demoAccounts': '데모 계정으로 빠른 로그인',
    'auth.studentAccount': '👨‍🎓 학생 계정',
    'auth.facultyAccount': '👨‍🏫 교직원 계정',
    'auth.masterAccount': '🔑 마스터 계정',
    'auth.adminSystem': '관리자 시스템',
    'auth.demoStudentDesc': '장지훈 (user1082) - 인문대학 / 국어국문학과 / 현대문학전공, 학생',
    'auth.demoFacultyDesc': '정수빈 (user1081) - 인문대학 / 국어국문학과 / 현대문학전공, 교수, 에이전트 관리자',
    'auth.demoMasterDesc': 'Master Admin (master_admin) - LoBo AI 챗봇 통합 관리자 센터 접근',
    'auth.autoCreate': '계정이 없는 경우 자동으로 생성됩니다',
    'auth.loginSuccess': '로그인 성공',
    'auth.welcome': '환영합니다!',
    'auth.loginFailed': '로그인 실패',
    'auth.loginError': '학번/교번 또는 비밀번호를 확인해주세요.',
    'auth.settings': '설정',
    'auth.themeSettings': '테마 설정',
    'auth.languageSettings': '언어 설정',
    'auth.usernameRequired': '학번/교번을 입력해주세요',
    'auth.passwordRequired': '비밀번호를 입력해주세요',
    'auth.passwordMinLength': '비밀번호는 6자 이상이어야 합니다',
    'auth.firstNameRequired': '이름을 입력해주세요',
    'auth.lastNameRequired': '성을 입력해주세요',
    'auth.emailInvalid': '올바른 이메일 주소를 입력해주세요',
    
    // 공통 UI 요소
    'common.home': '홈',
    'common.chat': '채팅',
    'common.management': '관리',
    'common.logout': '로그아웃',
    'common.loading': '로딩 중...',
    'common.search': '검색',
    'common.files': '파일',
    'common.settings': '설정',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.delete': '삭제',
    'common.edit': '수정',
    'common.upload': '업로드',
    'common.download': '다운로드',
    'common.error': '오류',
    'common.success': '성공',
    
    // 홈페이지
    'home.searchPlaceholder': '에이전트 검색...',
    'home.categories.all': '전체',
    'home.categories.school': '학교',
    'home.categories.professor': '교수',
    'home.categories.student': '학생',
    'home.categories.group': '그룹',
    'home.categories.function': '기능형',
    'home.accountSettings': '계정 설정',
    'home.selectAgent': '에이전트를 선택하세요',
    'home.selectAgentDesc': '왼쪽에서 대화하고 싶은 에이전트를 선택하면 여기에 채팅창이 나타납니다.',
    'home.manageAgent': '관리할 에이전트를 선택하세요',
    'home.manageAgentDesc': '왼쪽에서 관리하고 싶은 에이전트를 선택하면 여기에 관리 인터페이스가 나타납니다.',
    
    // 에이전트 관리
    'agent.management': '에이전트 관리',
    'agent.managementDesc': '관리 중인 에이전트를 선택하여 설정하세요',
    'agent.persona': '페르소나',
    'agent.iconChange': '아이콘 변경',
    'agent.settings': '챗봇 설정',
    'agent.notification': '알림보내기',
    'agent.upload': '문서 업로드',
    'agent.performance': '성과 분석',
    'agent.active': '활성',
    'agent.chat': '에이전트 채팅',
    'agent.agentManagement': '에이전트 관리',
    'agent.functionsSelect': '기능선택',
    'agent.totalUsers': '총 메시지',
    'agent.satisfaction': '사용률',
    'agent.ranking': '순위',
    'agent.managementMode': '관리자 모드',
    'agent.generalChat': '채팅',
    
    // Chat interface
    'chat.typing': '메시지 작성 중...',
    'chat.inputPlaceholder': '메시지를 입력하세요...',
    
    // 마스터 관리자 센터
    'admin.title': 'LoBo AI 관리자 센터',
    'admin.subtitle': '대학교 AI 챗봇 서비스 통합 관리',
    'admin.dashboard': '대시보드',
    'admin.categories': '조직 카테고리 관리',
    'admin.users': '사용자 관리',
    'admin.agents': '에이전트 관리',
    'admin.documents': '문서 관리',
    'admin.conversations': '질문/응답 로그',
    'admin.tokens': '토큰 관리',
    'admin.system': '시스템 설정',
    'admin.logout': '로그아웃',
    'admin.chatbot': 'LoBo 챗봇',
    'admin.totalUsers': '총 사용자',
    'admin.totalAgents': '총 에이전트',
    'admin.totalConversations': '총 대화',
    'admin.totalTokens': '총 토큰',
    'admin.todayActivity': '오늘 활동',
    'admin.systemStatus': '시스템 상태',
    'admin.activeUsers': '활성 사용자',
    'admin.activeAgents': '활성 에이전트',
    'admin.totalMessages': '총 메시지',
    'admin.weeklyGrowth': '주간 증가율',
    'admin.recentActivity': '최근 활동',
    'admin.database': '데이터베이스',
    'admin.openaiApi': 'OpenAI API',
    'admin.sessionStore': '세션 스토어',
    'admin.fileUpload': '파일 업로드',
    'admin.status.healthy': '정상',
    'admin.status.error': '오류',
    'admin.organizationManagement': '조직 카테고리 관리',
    'admin.userManagement': '사용자 관리',
    'admin.agentManagement': '에이전트 관리',
    'admin.documentManagement': '문서 관리',
    'admin.qaLogs': '질문/응답 로그',
    'admin.tokenManagement': '토큰 관리',
    'admin.systemSettings': '시스템 설정',
    'admin.todayQuestionsTitle': '오늘 질문 수',
    'admin.avgResponseTimeTitle': '평균 응답 시간',
    'admin.responseFailureTitle': '응답 실패율',
    'admin.userSatisfactionTitle': '사용자 만족도',
    'admin.userSearch': '사용자 검색',
    'admin.organizationSearch': '조직 검색 및 관리',
    'admin.agentSearch': '에이전트 검색 및 관리',
    'admin.filterByOrganization': '필터 초기화',
    'admin.search': '검색',
    'admin.download': '다운로드',
    'admin.addUser': '사용자 추가',
    'admin.addOrganization': '새 조직 카테고리 추가',
    'admin.lmsSync': 'LMS 연동 (권장)',
    'admin.fileUploadDesc': '파일 업로드',
    'admin.organizationList': '조직 목록',
    
    // Organization Management
    'org.lmsIntegration': 'LMS 연동 (권장)',
    'org.fileUpload': '파일 업로드',
    'org.categorySearchManagement': '조직 카테고리 검색 및 관리',
    'org.upperOrganization': '상위조직',
    'org.all': '전체',
    'org.lowerOrganization': '하위조직',
    'org.detailOrganization': '세부조직',
    'org.resetFilters': '필터 초기화',
    'org.organizationList': '조직 목록',
    'org.totalOrganizations': '전체 124개 조직 중 1-20개 표시',
    'org.upperOrg': '상위 조직',
    'org.lowerOrg': '하위 조직',
    'org.detailOrg': '세부 조직',
    'org.manager': '관리자',
    'org.memberCount': '소속 인원',
    'org.agentCount': '에이전트 수',
    'org.status': '상태',
    'org.select': '선택',
    'admin.userList': '사용자 목록',
    
    // Document Management Korean
    'doc.fileType': '파일 형식',
    'doc.fileRequirements': '파일 형식 요구사항',
    'doc.inactiveFiles': '비활성 문서',
    'doc.totalCapacity': '총 용량',
    'doc.others': '기타',
    'doc.resetFilters': '필터 초기화',
    'doc.searchResults': '검색 결과',
    'doc.searchKeyword': '검색어',

    // Organization Management
    'org.searchAndManagement': '조직 카테고리 검색 및 관리',
    'org.upperCategory': '상위조직',
    'org.lowerCategory': '하위조직', 
    'org.detailCategory': '세부조직',
    'org.organizationSearch': '조직 검색',
    'org.searchPlaceholder': '조직명으로 검색...',
    
    // Q&A and Token Management
    'admin.qaManagement': 'Q&A 관리',
    'admin.todayQuestionsTitle': '오늘 질문 수',
    'admin.todayQuestions': '247',
    'admin.avgResponseTimeTitle': '평균 응답 시간',
    'admin.avgResponseTime': '2.3초',
    'admin.responseSuccessTitle': '질문 응답 성공률',
    'admin.responseSuccess': '96.8%',
    'admin.userSatisfactionTitle': '응답 사용자 만족도',
    'admin.userSatisfactionValue': '4.6/5',
    'admin.dailyAverageTitle': '토큰 소비량 일평균',
    'admin.dailyAverage': '2.6K',
    'admin.estimatedCostTitle': '토큰 예상 비용',
    'admin.estimatedCost': '₩6,761',
    'admin.inputAverageTitle': '토큰 투입량 평균',
    'admin.inputAverage': '73%',
    'admin.popularQuestionsTitle': '인기 질문 TOP 5',
    'admin.systemStatusTitle': 'System Status',
    
    // Q&A Logs specific
    'admin.userType': '사용자 유형',
    'admin.period': '기간',
    'admin.questionSearch': '질문 내용으로 검색하세요.',
    'admin.responseMethod': '응답 방식',
    'admin.responseFail': '응답 실패',
    'admin.improvementRequest': '개선 요청',
    'admin.organizationAffiliation': '조직 소속',
    'admin.question': '질문',
    'admin.answer': '답변',
    'admin.responseTime': '응답 시간',
    'admin.time': '시간',
    'admin.organization': '소속 조직',
    'admin.conversationTime': '대화 시각',
    'admin.agent': '에이전트',
    'admin.responseStatus': '응답 상태',
    'admin.questionContent': '질문 내용',
    'admin.responseContent': '응답 내용',
    'admin.improveComment': '개선 요청 코멘트',
    'admin.improveCommentPlaceholder': '개선이 필요한 내용을 입력해주세요.',
    'admin.success': '성공',
    'admin.failure': '실패',
    'admin.like': '좋아요',
    'admin.dislike': '싫어요',
    'admin.unknown': '알 수 없음',
    'admin.noQuestionContent': '질문 내용이 없습니다',
    'admin.noResponseContent': '응답 내용이 없습니다',
    'admin.improveRequestTitle': '개선 요청 및 코멘트',
    'admin.improveRequestDesc': '질의응답에 대한 개선 요청과 코멘트를 작성합니다.',
    'admin.questionAnswerDetailTitle': '질문응답 상세보기',
    'admin.questionAnswerDetailDesc': '질의응답 세부 정보를 확인합니다.',
    
    // 언어 이름
    'language.ko': '한국어',
    'language.en': 'English',
    'language.zh': '中文',
    'language.vi': 'Tiếng Việt',
    'language.ja': '日本語',
  },
  
  en: {
    // Login page
    'auth.title': 'LoBo',
    'auth.subtitle': 'University AI Chatbot System',
    'auth.login': 'Login',
    'auth.username': 'Student/Faculty ID',
    'auth.usernamePlaceholder': 'e.g: 2024001234 or F2024001',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.forgotPasswordMessage': 'Contact administrator to reset your password.',
    'auth.loginButton': 'Login',
    'auth.loggingIn': 'Logging in...',
    'auth.demoAccounts': 'Quick login with demo accounts',
    'auth.studentAccount': '👨‍🎓 Student Account',
    'auth.facultyAccount': '👨‍🏫 Faculty Account',
    'auth.masterAccount': '🔑 Master Account',
    'auth.adminSystem': 'Admin System',
    'auth.demoStudentDesc': 'Jang Jihoon (user1082) - College of Liberal Arts / Korean Literature / Modern Literature, Student',
    'auth.demoFacultyDesc': 'Jung Subin (user1081) - College of Liberal Arts / Korean Literature / Modern Literature, Professor, Agent Manager',
    'auth.demoMasterDesc': 'Master Admin (master_admin) - LoBo AI Chatbot Integrated Management Center Access',
    'auth.autoCreate': 'Account will be created automatically if not exists',
    'auth.loginSuccess': 'Login Successful',
    'auth.welcome': 'Welcome!',
    'auth.loginFailed': 'Login Failed',
    'auth.loginError': 'Please check your ID or password.',
    'auth.settings': 'Settings',
    'auth.themeSettings': 'Theme Settings',
    'auth.languageSettings': 'Language Settings',
    'auth.usernameRequired': 'Please enter your ID',
    'auth.passwordRequired': 'Please enter password',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.firstNameRequired': 'Please enter first name',
    'auth.lastNameRequired': 'Please enter last name',
    'auth.emailInvalid': 'Please enter a valid email address',
    
    // Common UI elements
    'common.home': 'Home',
    'common.chat': 'Chat',
    'common.management': 'Management',
    'common.logout': 'Logout',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.files': 'Files',
    'common.settings': 'Settings',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Organization Management
    'org.lmsIntegration': 'LMS Integration (Recommended)',
    'org.fileUpload': 'File Upload',
    'org.categorySearchManagement': 'Organization Category Search & Management',
    'org.upperOrganization': 'Upper Organization',
    'org.all': 'All',
    'org.lowerOrganization': 'Lower Organization',
    'org.detailOrganization': 'Detail Organization',
    'org.organizationList': 'Organization List',
    'org.totalOrganizations': 'Showing 1-20 of 124 total organizations',
    'org.upperOrg': 'Upper Organization',
    'org.lowerOrg': 'Lower Organization',
    'org.detailOrg': 'Detail Organization',
    'org.manager': 'Manager',
    'org.memberCount': 'Member Count',
    'org.agentCount': 'Agent Count',
    'org.status': 'Status',
    'org.select': 'Select',

    // Homepage
    'home.searchPlaceholder': 'Search agents...',
    'home.categories.all': 'All',
    'home.categories.school': 'School',
    'home.categories.professor': 'Professor',
    'home.categories.student': 'Student',
    'home.categories.group': 'Group',
    'home.categories.function': 'Function',
    'home.accountSettings': 'Account Settings',
    'home.selectAgent': 'Select an agent',
    'home.selectAgentDesc': 'Choose an agent from the left to start chatting.',
    'home.manageAgent': 'Select an agent to manage',
    'home.manageAgentDesc': 'Choose an agent from the left to access management interface.',
    
    // Agent management
    'agent.management': 'Agent Management',
    'agent.managementDesc': 'Select a managed agent to configure settings',
    'agent.persona': 'Persona',
    'agent.iconChange': 'Change Icon',
    'agent.settings': 'Bot Settings',
    'agent.notification': 'Send Notification',
    'agent.upload': 'Upload Document',
    'agent.performance': 'Performance Analysis',
    'agent.active': 'Active',
    'agent.chat': 'Agent Chat',
    'agent.agentManagement': 'Agent Management',
    'agent.functionsSelect': 'Functions',
    'agent.totalUsers': 'Total Messages',
    'agent.satisfaction': 'Usage Rate',
    'agent.ranking': 'Ranking',
    'agent.managementMode': 'Management Mode',
    'agent.generalChat': 'General Chat',
    
    // Chat interface
    'chat.typing': 'Typing...',
    'chat.inputPlaceholder': 'Type a message...',
    
    // Document Management
    'doc.management': 'Document Management',
    'doc.lmsConnected': 'LMS Connected',
    'doc.lmsDescription': 'LMS system allows automatic document and content import.',
    'doc.directUpload': 'Direct Upload',
    'doc.directUploadDescription': 'PDF, Word, Excel files can be uploaded directly.',
    'doc.statistics': 'Document Statistics',
    'doc.searchAndManagement': 'Document Search & Management',
    'doc.totalFiles': 'Total Files',
    'doc.wordFiles': 'Word Files',
    'doc.excelFiles': 'Excel Files',
    'doc.pdfFiles': 'PDF Files',
    'doc.etc': 'Other',
    'doc.totalSize': 'Total Size',
    'doc.recentUploads': 'Recent Uploads',
    'doc.fileName': 'File Name',
    'doc.category': 'Category',
    'doc.manager': 'Manager',
    'doc.uploadDate': 'Upload Date',
    'doc.searchPlaceholder': 'Search by file name, category, manager...',
    'doc.search': 'Search',
    'doc.fileType': 'File Type',
    'doc.fileRequirements': 'File Format Requirements',
    'doc.inactiveFiles': 'Inactive Documents',
    'doc.totalCapacity': 'Total Capacity',
    'doc.others': 'Others',
    'doc.resetFilters': 'Reset Filters',
    'doc.searchResults': 'Search Results: {count} documents',
    'doc.searchKeyword': 'Search Keyword',

    // Organization Management
    'org.searchAndManagement': 'Organization Category Search & Management',
    'org.upperCategory': 'Upper Organization',
    'org.lowerCategory': 'Lower Organization', 
    'org.detailCategory': 'Detail Organization',
    'org.organizationSearch': 'Organization Search',
    'org.searchPlaceholder': 'Search by organization name...',

    // Master Admin Center
    'admin.title': 'LoBo AI Admin Center',
    'admin.subtitle': 'University AI Chatbot Service Integrated Management',
    'admin.dashboard': 'Dashboard',
    'admin.categories': 'Organization Category Management',
    'admin.users': 'User Management',
    'admin.agents': 'Agent Management',
    'admin.documents': 'Document Management',
    'admin.conversations': 'Q&A Logs',
    'admin.tokens': 'Token Management',
    'admin.system': 'System Settings',
    'admin.logout': 'Logout',
    'admin.chatbot': 'LoBo Chatbot',
    'admin.totalUsers': 'Total Users',
    'admin.totalAgents': 'Total Agents',
    'admin.totalConversations': 'Total Conversations',
    'admin.totalTokens': 'Total Tokens',
    'admin.todayActivity': 'Today\'s Activity',
    'admin.systemStatus': 'System Status',
    'admin.activeUsers': 'Active Users',
    'admin.activeAgents': 'Active Agents',
    'admin.totalMessages': 'Total Messages',
    'admin.weeklyGrowth': 'Weekly Growth',
    'admin.recentActivity': 'Recent Activity',
    'admin.database': 'Database',
    'admin.openaiApi': 'OpenAI API',
    'admin.sessionStore': 'Session Store',
    'admin.fileUpload': 'File Upload',
    'admin.status.healthy': 'Healthy',
    'admin.status.error': 'Error',
    'admin.organizationManagement': 'Organization Category Management',
    'admin.userManagement': 'User Management',
    'admin.agentManagement': 'Agent Management',
    'admin.documentManagement': 'Document Management',
    'admin.qaLogs': 'Q&A Logs',
    'admin.tokenManagement': 'Token Management',
    'admin.systemSettings': 'System Settings',
    'admin.todayQuestionsTitle': 'Today\'s Questions',
    'admin.avgResponseTimeTitle': 'Avg Response Time',
    'admin.responseFailureTitle': 'Response Failure Rate',
    'admin.userSatisfactionTitle': 'User Satisfaction',
    'admin.userSearch': 'User Search',
    'admin.organizationSearch': 'Organization Search & Management',
    'admin.agentSearch': 'Agent Search & Management',
    'admin.filterByOrganization': 'Reset Filters',
    'admin.search': 'Search',
    'admin.download': 'Download',
    'admin.addUser': 'Add User',
    'admin.addOrganization': 'Add New Organization Category',
    'admin.lmsSync': 'LMS Integration (Recommended)',
    'admin.fileUploadDesc': 'File Upload',
    'admin.organizationList': 'Organization List',
    'admin.userList': 'User List',
    
    // Q&A and Token Management English
    'admin.qaManagement': 'Q&A Management',
    'admin.todayQuestionsTitle': 'Today\'s Questions',
    'admin.todayQuestions': '247',
    'admin.avgResponseTimeTitle': 'Average Response Time',
    'admin.avgResponseTime': '2.3s',
    'admin.responseSuccessTitle': 'Response Success Rate',
    'admin.responseSuccess': '96.8%',
    'admin.userSatisfactionTitle': 'User Satisfaction',
    'admin.userSatisfactionValue': '4.6/5',
    'admin.dailyAverageTitle': 'Daily Token Usage',
    'admin.dailyAverage': '2.6K',
    'admin.estimatedCostTitle': 'Estimated Token Cost',
    'admin.estimatedCost': '$6,761',
    'admin.inputAverageTitle': 'Input Token Average',
    'admin.inputAverage': '73%',
    'admin.popularQuestionsTitle': 'Popular Questions TOP 5',
    'admin.systemStatusTitle': 'System Status',
    
    // Q&A Logs specific English
    'admin.userType': 'User Type',
    'admin.period': 'Period',
    'admin.questionSearch': 'Search by question content...',
    'admin.responseMethod': 'Response Method',
    'admin.responseFail': 'Response Failed',
    'admin.improvementRequest': 'Improvement Request',
    'admin.organizationAffiliation': 'Organization',
    'admin.question': 'Question',
    'admin.answer': 'Answer',
    'admin.responseTime': 'Response Time',
    'admin.time': 'Time',
    'admin.organization': 'Organization',
    'admin.conversationTime': 'Conversation Time',
    'admin.agent': 'Agent',
    'admin.responseStatus': 'Response Status',
    'admin.questionContent': 'Question Content',
    'admin.responseContent': 'Response Content',
    'admin.improveComment': 'Improvement Comment',
    'admin.improveCommentPlaceholder': 'Enter content that needs improvement...',
    'admin.success': 'Success',
    'admin.failure': 'Failed',
    'admin.like': 'Like',
    'admin.dislike': 'Dislike',
    'admin.unknown': 'Unknown',
    'admin.noQuestionContent': 'No question content available',
    'admin.noResponseContent': 'No response content available',
    'admin.improveRequestTitle': 'Improvement Request & Comment',
    'admin.improveRequestDesc': 'Write improvement requests and comments for Q&A.',
    'admin.questionAnswerDetailTitle': 'Question & Answer Details',
    'admin.questionAnswerDetailDesc': 'View detailed Q&A information.',
    
    // Language names
    'language.ko': '한국어',
    'language.en': 'English',
    'language.zh': '中文',
    'language.vi': 'Tiếng Việt',
    'language.ja': '日本語',
  },
  
  zh: {
    // 登录页面
    'auth.title': 'LoBo',
    'auth.subtitle': '大学人工智能聊天机器人系统',
    'auth.login': '登录',
    'auth.username': '学号/工号',
    'auth.usernamePlaceholder': '例: 2024001234 或 F2024001',
    'auth.password': '密码',
    'auth.passwordPlaceholder': '请输入密码',
    'auth.forgotPassword': '忘记密码？',
    'auth.forgotPasswordMessage': '请联系管理员重置密码。',
    'auth.loginButton': '登录',
    'auth.loggingIn': '登录中...',
    'auth.demoAccounts': '使用演示账户快速登录',
    'auth.studentAccount': '👨‍🎓 学生账户',
    'auth.facultyAccount': '👨‍🏫 教职员账户',
    'auth.masterAccount': '🔑 管理员账户',
    'auth.adminSystem': '管理系统',
    'auth.demoStudentDesc': '张志勋 (user1082) - 人文学院 / 韩国语言文学系 / 现代文学专业, 学生',
    'auth.demoFacultyDesc': '郑秀彬 (user1081) - 人文学院 / 韩国语言文学系 / 现代文学专业, 教授, 代理管理员',
    'auth.demoMasterDesc': '主管理员 (master_admin) - LoBo AI 聊天机器人集成管理中心访问',
    'auth.autoCreate': '如果账户不存在将自动创建',
    'auth.loginSuccess': '登录成功',
    'auth.welcome': '欢迎！',
    'auth.loginFailed': '登录失败',
    'auth.loginError': '请检查您的账号或密码。',
    'auth.settings': '设置',
    'auth.themeSettings': '主题设置',
    'auth.languageSettings': '语言设置',
    'auth.usernameRequired': '请输入学号/工号',
    'auth.passwordRequired': '请输入密码',
    'auth.passwordMinLength': '密码至少需要6个字符',
    'auth.firstNameRequired': '请输入姓名',
    'auth.lastNameRequired': '请输入姓氏',
    'auth.emailInvalid': '请输入有效的邮箱地址',
    
    // 通用UI元素
    'common.home': '首页',
    'common.chat': '聊天',
    'common.management': '管理',
    'common.logout': '登出',
    'common.search': '搜索',
    'common.files': '文件',
    'common.settings': '设置',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.upload': '上传',
    'common.download': '下载',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    
    // 首页
    'home.searchPlaceholder': '搜索智能助手...',
    'home.categories.all': '全部',
    'home.categories.school': '学校',
    'home.categories.professor': '教授',
    'home.categories.student': '学生',
    'home.categories.group': '群组',
    'home.categories.function': '功能型',
    'home.accountSettings': '账户设置',
    'home.selectAgent': '请选择智能助手',
    'home.selectAgentDesc': '从左侧选择一个智能助手开始对话。',
    'home.manageAgent': '请选择要管理的智能助手',
    'home.manageAgentDesc': '从左侧选择一个智能助手来访问管理界面。',
    
    // 智能助手管理
    'agent.management': '智能助手管理',
    'agent.managementDesc': '选择要配置的智能助手',
    'agent.persona': '角色设定',
    'agent.iconChange': '更换图标',
    'agent.settings': '机器人设置',
    'agent.notification': '发送通知',
    'agent.upload': '上传文档',
    'agent.performance': '性能分析',
    'agent.active': '活跃',
    'agent.totalUsers': '总消息数',
    'agent.satisfaction': '使用率',
    'agent.ranking': '排名',
    'agent.managementMode': '管理模式',
    'agent.generalChat': '一般对话',
    
    // Chat interface
    'chat.typing': '正在输入...',
    'chat.inputPlaceholder': '输入消息...',
    
    // 文档管理
    'doc.management': '文档管理',
    'doc.lmsConnected': 'LMS已连接',
    'doc.lmsDescription': 'LMS系统允许自动导入文档和内容。',
    'doc.directUpload': '直接上传',
    'doc.directUploadDescription': '可以直接上传PDF、Word、Excel文件。',
    'doc.statistics': '文档统计',
    'doc.searchAndManagement': '文档搜索与管理',
    'doc.totalFiles': '总文件数',
    'doc.wordFiles': 'Word文件',
    'doc.excelFiles': 'Excel文件',
    'doc.pdfFiles': 'PDF文件',
    'doc.etc': '其他',
    'doc.totalSize': '总大小',
    'doc.recentUploads': '最近上传',
    'doc.fileName': '文件名',
    'doc.category': '类别',
    'doc.manager': '管理员',
    'doc.uploadDate': '上传日期',
    'doc.searchPlaceholder': '按文件名、类别、管理员搜索...',
    'doc.search': '搜索',
    'doc.fileType': '文件类型',
    'doc.fileRequirements': '文件格式要求',
    'doc.inactiveFiles': '非活动文档',
    'doc.totalCapacity': '总容量',
    'doc.others': '其他',
    'doc.resetFilters': '重置筛选',
    'doc.searchResults': '搜索结果：{count}个文档',
    'doc.searchKeyword': '搜索关键词',
    
    // 主管理员中心
    'admin.title': 'LoBo AI 管理中心',
    'admin.subtitle': '大学 AI 聊天机器人服务集成管理',
    'admin.dashboard': '仪表板',
    'admin.categories': '组织类别管理',
    'admin.users': '用户管理',
    'admin.agents': '智能助手管理',
    'admin.documents': '文档管理',
    'admin.conversations': '问答日志',
    'admin.tokens': '令牌管理',
    'admin.system': '系统设置',
    'admin.logout': '登出',
    'admin.chatbot': 'LoBo 聊天机器人',
    'admin.totalUsers': '总用户数',
    'admin.totalAgents': '总智能助手数',
    'admin.totalConversations': '总对话数',
    'admin.totalTokens': '总令牌数',
    'admin.todayActivity': '今日活动',
    'admin.systemStatus': '系统状态',
    'admin.activeUsers': '活跃用户',
    'admin.activeAgents': '活跃智能助手',
    'admin.totalMessages': '总消息数',
    'admin.weeklyGrowth': '周增长率',
    'admin.recentActivity': '最近活动',
    'admin.database': '数据库',
    'admin.openaiApi': 'OpenAI API',
    'admin.sessionStore': '会话存储',
    'admin.fileUpload': '文件上传',
    'admin.status.healthy': '正常',
    'admin.status.error': '错误',
    'admin.organizationManagement': '组织类别管理',
    'admin.userManagement': '用户管理',
    'admin.agentManagement': '智能助手管理',
    'admin.documentManagement': '文档管理',
    'admin.qaLogs': '问答日志',
    'admin.tokenManagement': '令牌管理',
    'admin.systemSettings': '系统设置',
    'admin.todayQuestionsTitle': '今日问题数',
    'admin.avgResponseTimeTitle': '平均响应时间',
    'admin.responseFailureTitle': '响应失败率',
    'admin.userSatisfactionTitle': '用户满意度',
    'admin.userSearch': '用户搜索',
    'admin.organizationSearch': '组织搜索和管理',
    'admin.agentSearch': '智能助手搜索和管理',
    'admin.filterByOrganization': '重置过滤器',
    'admin.search': '搜索',
    'admin.download': '下载',
    'admin.addUser': '添加用户',
    'admin.addOrganization': '添加新组织类别',
    'admin.lmsSync': 'LMS 集成（推荐）',
    'admin.fileUploadDesc': '文件上传',
    'admin.organizationList': '组织列表',
    
    // Organization Management
    'org.lmsIntegration': 'LMS集成 (推荐)',
    'org.fileUpload': '文件上传',
    'org.categorySearchManagement': '组织类别搜索与管理',
    'org.upperOrganization': '上级组织',
    'org.all': '全部',
    'org.lowerOrganization': '下级组织',
    'org.detailOrganization': '详细组织',
    'org.resetFilters': '重置筛选',
    'org.organizationList': '组织列表',
    'org.totalOrganizations': '显示124个组织中的1-20个',
    'org.upperOrg': '上级组织',
    'org.lowerOrg': '下级组织',
    'org.detailOrg': '详细组织',
    'org.manager': '管理员',
    'org.memberCount': '成员数量',
    'org.agentCount': '代理数量',
    'org.status': '状态',
    'org.select': '选择',
    'admin.userList': '用户列表',
    
    // 语言名称
    'language.ko': '한국어',
    'language.en': 'English',
    'language.zh': '中文',
    'language.vi': 'Tiếng Việt',
    'language.ja': '日本語',
  },
  
  vi: {
    // Trang đăng nhập
    'auth.title': 'LoBo',
    'auth.subtitle': 'Hệ thống Chatbot AI Trường đại học',
    'auth.login': 'Đăng nhập',
    'auth.username': 'Mã số sinh viên/giảng viên',
    'auth.usernamePlaceholder': 'VD: 2024001234 hoặc F2024001',
    'auth.password': 'Mật khẩu',
    'auth.passwordPlaceholder': 'Nhập mật khẩu của bạn',
    'auth.forgotPassword': 'Quên mật khẩu?',
    'auth.forgotPasswordMessage': 'Liên hệ quản trị viên để đặt lại mật khẩu.',
    'auth.loginButton': 'Đăng nhập',
    'auth.loggingIn': 'Đang đăng nhập...',
    'auth.demoAccounts': 'Đăng nhập nhanh với tài khoản demo',
    'auth.studentAccount': '👨‍🎓 Tài khoản sinh viên',
    'auth.facultyAccount': '👨‍🏫 Tài khoản giảng viên',
    'auth.masterAccount': '🔑 Tài khoản quản trị',
    'auth.adminSystem': 'Hệ thống quản trị',
    'auth.demoStudentDesc': 'Jang Jihoon (user1082) - Khoa Nhân văn / Ngữ văn Hàn Quốc / Văn học hiện đại, Sinh viên',
    'auth.demoFacultyDesc': 'Jung Subin (user1081) - Khoa Nhân văn / Ngữ văn Hàn Quốc / Văn học hiện đại, Giáo sư, Quản lý Agent',
    'auth.demoMasterDesc': 'Quản trị viên chính (master_admin) - Truy cập Trung tâm quản lý tích hợp LoBo AI Chatbot',
    'auth.autoCreate': 'Tài khoản sẽ được tạo tự động nếu chưa tồn tại',
    'auth.loginSuccess': 'Đăng nhập thành công',
    'auth.welcome': 'Chào mừng!',
    'auth.loginFailed': 'Đăng nhập thất bại',
    'auth.loginError': 'Vui lòng kiểm tra mã số hoặc mật khẩu.',
    'auth.settings': 'Cài đặt',
    'auth.themeSettings': 'Cài đặt giao diện',
    'auth.languageSettings': 'Cài đặt ngôn ngữ',
    'auth.usernameRequired': 'Vui lòng nhập mã số',
    'auth.passwordRequired': 'Vui lòng nhập mật khẩu',
    'auth.passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
    'auth.firstNameRequired': 'Vui lòng nhập tên',
    'auth.lastNameRequired': 'Vui lòng nhập họ',
    'auth.emailInvalid': 'Vui lòng nhập địa chỉ email hợp lệ',
    
    // Các phần tử UI chung
    'common.home': 'Trang chủ',
    'common.chat': 'Trò chuyện',
    'common.management': 'Quản lý',
    'common.logout': 'Đăng xuất',
    'common.search': 'Tìm kiếm',
    'common.files': 'Tập tin',
    'common.settings': 'Cài đặt',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.delete': 'Xóa',
    'common.edit': 'Chỉnh sửa',
    'common.upload': 'Tải lên',
    'common.download': 'Tải xuống',
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    
    // Trang chủ
    'home.searchPlaceholder': 'Tìm kiếm trợ lý AI...',
    'home.categories.all': 'Tất cả',
    'home.categories.school': 'Trường học',
    'home.categories.professor': 'Giáo sư',
    'home.categories.student': 'Sinh viên',
    'home.categories.group': 'Nhóm',
    'home.categories.function': 'Chức năng',
    'home.accountSettings': 'Cài đặt tài khoản',
    'home.selectAgent': 'Vui lòng chọn trợ lý AI',
    'home.selectAgentDesc': 'Chọn một trợ lý AI từ bên trái để bắt đầu trò chuyện.',
    'home.manageAgent': 'Vui lòng chọn trợ lý AI để quản lý',
    'home.manageAgentDesc': 'Chọn một trợ lý AI từ bên trái để truy cập giao diện quản lý.',
    
    // Quản lý trợ lý AI
    'agent.management': 'Quản lý trợ lý AI',
    'agent.managementDesc': 'Chọn trợ lý AI để cấu hình cài đặt',
    'agent.persona': 'Nhân cách',
    'agent.iconChange': 'Thay đổi biểu tượng',
    'agent.settings': 'Cài đặt bot',
    'agent.notification': 'Gửi thông báo',
    'agent.upload': 'Tải lên tài liệu',
    'agent.performance': 'Phân tích hiệu suất',
    'agent.active': 'Hoạt động',
    'agent.totalUsers': 'Tổng tin nhắn',
    'agent.satisfaction': 'Tỷ lệ sử dụng',
    'agent.ranking': 'Xếp hạng',
    'agent.managementMode': 'Chế độ quản lý',
    'agent.generalChat': 'Trò chuyện thường',
    
    // Chat interface
    'chat.typing': 'Đang nhập...',
    'chat.inputPlaceholder': 'Nhập tin nhắn...',
    
    // Quản lý Tài liệu
    'doc.management': 'Quản lý Tài liệu',
    'doc.lmsConnected': 'LMS Đã kết nối',
    'doc.lmsDescription': 'Hệ thống LMS cho phép nhập tự động tài liệu và nội dung.',
    'doc.directUpload': 'Tải lên Trực tiếp',
    'doc.directUploadDescription': 'Có thể tải lên trực tiếp các tệp PDF, Word, Excel.',
    'doc.statistics': 'Thống kê Tài liệu',
    'doc.searchAndManagement': 'Tìm kiếm & Quản lý Tài liệu',
    'doc.totalFiles': 'Tổng số Tệp',
    'doc.wordFiles': 'Tệp Word',
    'doc.excelFiles': 'Tệp Excel',
    'doc.pdfFiles': 'Tệp PDF',
    'doc.etc': 'Khác',
    'doc.totalSize': 'Tổng dung lượng',
    'doc.recentUploads': 'Tải lên Gần đây',
    'doc.fileName': 'Tên Tệp',
    'doc.category': 'Danh mục',
    'doc.manager': 'Quản lý',
    'doc.uploadDate': 'Ngày tải lên',
    'doc.searchPlaceholder': 'Tìm theo tên tệp, danh mục, quản lý...',
    'doc.search': 'Tìm kiếm',
    'doc.fileType': 'Loại Tệp',
    'doc.fileRequirements': 'Yêu Cầu Định Dạng Tệp',
    'doc.inactiveFiles': 'Tài liệu không hoạt động',
    'doc.totalCapacity': 'Tổng dung lượng',
    'doc.others': 'Khác',
    'doc.resetFilters': 'Đặt lại Bộ lọc',
    'doc.searchResults': 'Kết quả tìm kiếm: {count} tài liệu',
    'doc.searchKeyword': 'Từ khóa tìm kiếm',
    
    // Trung tâm Quản trị chính
    'admin.title': 'LoBo AI Admin Center',
    'admin.subtitle': 'Quản lý Tích hợp Dịch vụ Chatbot AI Trường đại học',
    'admin.dashboard': 'Bảng điều khiển',
    'admin.categories': 'Quản lý Danh mục Tổ chức',
    'admin.users': 'Quản lý Người dùng',
    'admin.agents': 'Quản lý Trợ lý AI',
    'admin.documents': 'Quản lý Tài liệu',
    'admin.conversations': 'Nhật ký Hỏi đáp',
    'admin.tokens': 'Quản lý Token',
    'admin.system': 'Cài đặt Hệ thống',
    'admin.logout': 'Đăng xuất',
    'admin.chatbot': 'LoBo Chatbot',
    'admin.totalUsers': 'Tổng số Người dùng',
    'admin.totalAgents': 'Tổng số Trợ lý AI',
    'admin.totalConversations': 'Tổng số Cuộc trò chuyện',
    'admin.totalTokens': 'Tổng số Token',
    'admin.todayActivity': 'Hoạt động hôm nay',
    'admin.systemStatus': 'Trạng thái Hệ thống',
    'admin.activeUsers': 'Người dùng Hoạt động',
    'admin.activeAgents': 'Trợ lý AI Hoạt động',
    'admin.totalMessages': 'Tổng số Tin nhắn',
    'admin.weeklyGrowth': 'Tăng trưởng Hàng tuần',
    'admin.recentActivity': 'Hoạt động Gần đây',
    'admin.database': 'Cơ sở dữ liệu',
    'admin.openaiApi': 'OpenAI API',
    'admin.sessionStore': 'Lưu trữ Phiên',
    'admin.fileUpload': 'Tải lên Tệp',
    'admin.status.healthy': 'Tốt',
    'admin.status.error': 'Lỗi',
    'admin.organizationManagement': 'Quản lý Danh mục Tổ chức',
    'admin.userManagement': 'Quản lý Người dùng',
    'admin.agentManagement': 'Quản lý Trợ lý AI',
    'admin.documentManagement': 'Quản lý Tài liệu',
    'admin.qaLogs': 'Nhật ký Hỏi đáp',
    'admin.tokenManagement': 'Quản lý Token',
    'admin.systemSettings': 'Cài đặt Hệ thống',
    'admin.todayQuestionsTitle': 'Câu hỏi hôm nay',
    'admin.avgResponseTimeTitle': 'Thời gian phản hồi TB',
    'admin.responseFailureTitle': 'Tỷ lệ phản hồi thất bại',
    'admin.userSatisfactionTitle': 'Sự hài lòng người dùng',
    'admin.userSearch': 'Tìm kiếm Người dùng',
    'admin.organizationSearch': 'Tìm kiếm & Quản lý Tổ chức',
    'admin.agentSearch': 'Tìm kiếm & Quản lý Trợ lý AI',
    'admin.filterByOrganization': 'Đặt lại Bộ lọc',
    'admin.search': 'Tìm kiếm',
    'admin.download': 'Tải xuống',
    'admin.addUser': 'Thêm Người dùng',
    'admin.addOrganization': 'Thêm Danh mục Tổ chức Mới',
    'admin.lmsSync': 'Tích hợp LMS (Khuyến nghị)',
    'admin.fileUploadDesc': 'Tải lên Tệp',
    'admin.organizationList': 'Danh sách Tổ chức',
    
    // Organization Management
    'org.lmsIntegration': 'Tích hợp LMS (Khuyến nghị)',
    'org.fileUpload': 'Tải lên Tệp',
    'org.categorySearchManagement': 'Tìm kiếm và Quản lý Danh mục Tổ chức',
    'org.upperOrganization': 'Tổ chức Cấp trên',
    'org.all': 'Tất cả',
    'org.lowerOrganization': 'Tổ chức Cấp dưới',
    'org.detailOrganization': 'Tổ chức Chi tiết',
    'org.resetFilters': 'Đặt lại Bộ lọc',
    'org.organizationList': 'Danh sách Tổ chức',
    'org.totalOrganizations': 'Hiển thị 1-20 trong tổng số 124 tổ chức',
    'org.upperOrg': 'Tổ chức Cấp trên',
    'org.lowerOrg': 'Tổ chức Cấp dưới',
    'org.detailOrg': 'Tổ chức Chi tiết',
    'org.manager': 'Người quản lý',
    'org.memberCount': 'Số thành viên',
    'org.agentCount': 'Số trợ lý AI',
    'org.status': 'Trạng thái',
    'org.select': 'Chọn',
    'admin.userList': 'Danh sách Người dùng',
    
    // Tên ngôn ngữ
    'language.ko': '한국어',
    'language.en': 'English',
    'language.zh': '中文',
    'language.vi': 'Tiếng Việt',
    'language.ja': '日本語',
  },
  
  ja: {
    // ログインページ
    'auth.title': 'LoBo',
    'auth.subtitle': '大学AIチャットボットシステム',
    'auth.login': 'ログイン',
    'auth.username': '学籍番号/職員番号',
    'auth.usernamePlaceholder': '例: 2024001234 または F2024001',
    'auth.password': 'パスワード',
    'auth.passwordPlaceholder': 'パスワードを入力してください',
    'auth.forgotPassword': 'パスワードをお忘れですか？',
    'auth.forgotPasswordMessage': '管理者に連絡してパスワードをリセットしてください。',
    'auth.loginButton': 'ログイン',
    'auth.loggingIn': 'ログイン中...',
    'auth.demoAccounts': 'デモアカウントでクイックログイン',
    'auth.studentAccount': '👨‍🎓 学生アカウント',
    'auth.facultyAccount': '👨‍🏫 教職員アカウント',
    'auth.masterAccount': '🔑 マスターアカウント',
    'auth.adminSystem': '管理システム',
    'auth.demoStudentDesc': 'チャン・ジフン (user1082) - 人文学部 / 韓国語文学科 / 現代文学専攻, 学生',
    'auth.demoFacultyDesc': 'チョン・スビン (user1081) - 人文学部 / 韓国語文学科 / 現代文学専攻, 教授, エージェント管理者',
    'auth.demoMasterDesc': 'マスター管理者 (master_admin) - LoBo AI チャットボット統合管理センターアクセス',
    'auth.autoCreate': 'アカウントが存在しない場合は自動作成されます',
    'auth.loginSuccess': 'ログイン成功',
    'auth.welcome': 'ようこそ！',
    'auth.loginFailed': 'ログイン失敗',
    'auth.loginError': '学籍番号/職員番号またはパスワードを確認してください。',
    'auth.settings': '設定',
    'auth.themeSettings': 'テーマ設定',
    'auth.languageSettings': '言語設定',
    'auth.usernameRequired': '学籍番号/職員番号を入力してください',
    'auth.passwordRequired': 'パスワードを入力してください',
    'auth.passwordMinLength': 'パスワードは6文字以上である必要があります',
    'auth.firstNameRequired': '名前を入力してください',
    'auth.lastNameRequired': '姓を入力してください',
    'auth.emailInvalid': '有効なメールアドレスを入力してください',
    
    // 共通UI要素
    'common.home': 'ホーム',
    'common.chat': 'チャット',
    'common.management': '管理',
    'common.logout': 'ログアウト',
    'common.search': '検索',
    'common.files': 'ファイル',
    'common.settings': '設定',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.upload': 'アップロード',
    'common.download': 'ダウンロード',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    
    // ホームページ
    'home.searchPlaceholder': 'エージェント検索...',
    'home.categories.all': 'すべて',
    'home.categories.school': '学校',
    'home.categories.professor': '教授',
    'home.categories.student': '学生',
    'home.categories.group': 'グループ',
    'home.categories.function': '機能型',
    'home.accountSettings': 'アカウント設定',
    'home.selectAgent': 'エージェントを選択してください',
    'home.selectAgentDesc': '左側からエージェントを選択してチャットを開始してください。',
    'home.manageAgent': '管理するエージェントを選択してください',
    'home.manageAgentDesc': '左側からエージェントを選択して管理インターフェースにアクセスしてください。',
    
    // エージェント管理
    'agent.management': 'エージェント管理',
    'agent.managementDesc': '管理するエージェントを選択して設定してください',
    'agent.persona': 'ペルソナ',
    'agent.iconChange': 'アイコン変更',
    'agent.settings': 'ボット設定',
    'agent.notification': '通知送信',
    'agent.upload': 'ドキュメントアップロード',
    'agent.performance': 'パフォーマンス分析',
    'agent.active': 'アクティブ',
    'agent.totalUsers': '総メッセージ数',
    'agent.satisfaction': '使用率',
    'agent.ranking': 'ランキング',
    'agent.managementMode': '管理モード',
    'agent.generalChat': '一般チャット',
    
    // Chat interface
    'chat.typing': '入力中...',
    'chat.inputPlaceholder': 'メッセージを入力...',
    
    // ドキュメント管理
    'doc.management': 'ドキュメント管理',
    'doc.lmsConnected': 'LMS接続済み',
    'doc.lmsDescription': 'LMSシステムにより自動的にドキュメントとコンテンツをインポートできます。',
    'doc.directUpload': '直接アップロード',
    'doc.directUploadDescription': 'PDF、Word、Excelファイルを直接アップロードできます。',
    'doc.statistics': 'ドキュメント統計',
    'doc.searchAndManagement': 'ドキュメント検索・管理',
    'doc.totalFiles': '総ファイル数',
    'doc.wordFiles': 'Wordファイル',
    'doc.excelFiles': 'Excelファイル',
    'doc.pdfFiles': 'PDFファイル',
    'doc.etc': 'その他',
    'doc.totalSize': '総サイズ',
    'doc.recentUploads': '最近のアップロード',
    'doc.fileName': 'ファイル名',
    'doc.category': 'カテゴリー',
    'doc.manager': '管理者',
    'doc.uploadDate': 'アップロード日',
    'doc.searchPlaceholder': 'ファイル名、カテゴリー、管理者で検索...',
    'doc.search': '検索',
    'doc.fileType': 'ファイル形式',
    'doc.fileRequirements': 'ファイル形式要件',
    'doc.inactiveFiles': '非アクティブな文書',
    'doc.totalCapacity': '総容量',
    'doc.others': 'その他',
    'doc.resetFilters': 'フィルターをリセット',
    'doc.searchResults': '検索結果：{count}個の文書',
    'doc.searchKeyword': '検索キーワード',
    
    // マスター管理センター
    'admin.title': 'LoBo AI 管理センター',
    'admin.subtitle': '大学 AI チャットボットサービス統合管理',
    'admin.dashboard': 'ダッシュボード',
    'admin.categories': '組織カテゴリー管理',
    'admin.users': 'ユーザー管理',
    'admin.agents': 'エージェント管理',
    'admin.documents': 'ドキュメント管理',
    'admin.conversations': '質問・回答ログ',
    'admin.tokens': 'トークン管理',
    'admin.system': 'システム設定',
    'admin.logout': 'ログアウト',
    'admin.chatbot': 'LoBo チャットボット',
    'admin.totalUsers': '総ユーザー数',
    'admin.totalAgents': '総エージェント数',
    'admin.totalConversations': '総対話数',
    'admin.totalTokens': '総トークン数',
    'admin.todayActivity': '今日のアクティビティ',
    'admin.systemStatus': 'システムステータス',
    'admin.activeUsers': 'アクティブユーザー',
    'admin.activeAgents': 'アクティブエージェント',
    'admin.totalMessages': '総メッセージ数',
    'admin.weeklyGrowth': '週間成長率',
    'admin.recentActivity': '最近のアクティビティ',
    'admin.database': 'データベース',
    'admin.openaiApi': 'OpenAI API',
    'admin.sessionStore': 'セッションストア',
    'admin.fileUpload': 'ファイルアップロード',
    'admin.status.healthy': '正常',
    'admin.status.error': 'エラー',
    'admin.organizationManagement': '組織カテゴリー管理',
    'admin.userManagement': 'ユーザー管理',
    'admin.agentManagement': 'エージェント管理',
    'admin.documentManagement': 'ドキュメント管理',
    'admin.qaLogs': 'Q&Aログ',
    'admin.tokenManagement': 'トークン管理',
    'admin.systemSettings': 'システム設定',
    'admin.todayQuestionsTitle': '今日の質問数',
    'admin.avgResponseTimeTitle': '平均応答時間',
    'admin.responseFailureTitle': '応答失敗率',
    'admin.userSatisfactionTitle': 'ユーザー満足度',
    'admin.userSearch': 'ユーザー検索',
    'admin.organizationSearch': '組織検索・管理',
    'admin.agentSearch': 'エージェント検索・管理',
    'admin.filterByOrganization': 'フィルターリセット',
    'admin.search': '検索',
    'admin.download': 'ダウンロード',
    'admin.addUser': 'ユーザー追加',
    'admin.addOrganization': '新組織カテゴリー追加',
    'admin.lmsSync': 'LMS連携（推奨）',
    'admin.fileUploadDesc': 'ファイルアップロード',
    'admin.organizationList': '組織リスト',
    
    // Organization Management
    'org.lmsIntegration': 'LMS連携 (推奨)',
    'org.fileUpload': 'ファイルアップロード',
    'org.categorySearchManagement': '組織カテゴリ検索・管理',
    'org.upperOrganization': '上位組織',
    'org.all': 'すべて',
    'org.lowerOrganization': '下位組織',
    'org.detailOrganization': '詳細組織',
    'org.resetFilters': 'フィルタリセット',
    'org.organizationList': '組織リスト',
    'org.totalOrganizations': '全124組織中1-20件表示',
    'org.upperOrg': '上位組織',
    'org.lowerOrg': '下位組織',
    'org.detailOrg': '詳細組織',
    'org.manager': '管理者',
    'org.memberCount': 'メンバー数',
    'org.agentCount': 'エージェント数',
    'org.status': 'ステータス',
    'org.select': '選択',
    'admin.userList': 'ユーザーリスト',
    
    // 言語名
    'language.ko': '한국어',
    'language.en': 'English',
    'language.zh': '中文',
    'language.vi': 'Tiếng Việt',
    'language.ja': '日本語',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>('ko');

  // 로컬 스토리지에서 언어 설정 로드
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // 언어 변경 시 로컬 스토리지에 저장
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  // 번역 함수
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};